### ISSUE TITLE
New replaygain backend bs1770gain failing

### ISSUE THREAD

**Issue by bossanova808** [beetbox/beets#1398] opened 2015-04-07 03:18 UTC
Hi Folks

trying the new backend out - very handy to at last have an easier option on Windows.  However, hitting a hurdle pretty quick on testing:

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.3.11', 'console_scripts', 'beet')()
  File "C:\Python27\lib\site-packages\beets\ui\__init__.py", line 1081, in main
    _raw_main(args)
  File "C:\Python27\lib\site-packages\beets\ui\__init__.py", line 1071, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Python27\lib\site-packages\beets\ui\commands.py", line 892, in import_func
    import_files(lib, paths, query)
  File "C:\Python27\lib\site-packages\beets\ui\commands.py", line 869, in import_files
    session.run()
  File "C:\Python27\lib\site-packages\beets\importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "C:\Python27\lib\site-packages\beets\util\pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "C:\Python27\lib\site-packages\beets\util\pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "C:\Python27\lib\site-packages\beets\importer.py", line 1343, in plugin_stage
    func(session, task)
  File "C:\Python27\lib\site-packages\beets\plugins.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\beetsplug\replaygain.py", line 849, in imported
    self.handle_album(task.album, False)
  File "C:\Python27\lib\site-packages\beetsplug\replaygain.py", line 790, in handle_album
    album_gain = self.backend_instance.compute_album_gain(album)
  File "C:\Python27\lib\site-packages\beetsplug\replaygain.py", line 133, in compute_album_gain
    return AlbumGain(output[-1], output[:-1])
IndexError: list index out of range
```

My config is:

```
library: C:\Utilities\beets\library.db
directory: F:\TestOut
import:
    copy: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beets.log
ignore: .AppleDouble ._* *~ .DS_Store
art_filename: folder
original_date: yes
ui:
    color: yes
#plugins: scrub chroma lyrics fetchart embedart ftintitle missing 
plugins: scrub chroma lyrics fetchart embedart replaygain ftintitle missing 
threaded: yes
id3v23: yes
paths:
    default: $albumartist/$year - $album%aunique{}/$track $title
    singleton: Singles/$year/$artist - $title
    comp: Various Artists/$year - $album%aunique{}/$track $title (by $artist)
lastgenre:
    count: 3
#bs1770gain.exe must be in $PATH
replaygain:
    backend: bs1770gain
    overwrite: yes
    albumgain: yes
fetchart:
    cautious: true
    cover_names: front back cover folder
```

Error happens with albumgain enabled or not.  Not sure if this is still used, couldn't see it in the docs.

Any clues on this one?

**Comment by sampsyo** [comment] 2015-04-07 03:22
@jmwatte, would you mind taking a look? I added you as a collaborator so I could assign this to you. :smiley:

It looks like the output parser may need to tolerate malformed output. Just logging an error in this case and failing would be fine—but having the actual output from the underlying tool in the debug log would be useful to understand exactly what's going wrong.

**Comment by jmwatte** [comment] 2015-04-07 06:24
I'm looking into it... got a free day tomorrow. Do not have a windows-machine. I'll see what we can do.

**Comment by bossanova808** [comment] 2015-04-07 08:20
Happy to help with any output etc, can run from git if required no worries.

Doesn't work at all on windows currently, tried with 4 albums that all import fine without this.

**Comment by jmwatte** [comment] 2015-04-07 09:30
Just a quick one ...
can you run

bs1770gain.exe path_to_album_folder --replaygain --file "testresults.txt"

​and post me the output.
This should put an analyses of your album with replaygain in a textfile
named testresults.
Just to make sure that bs1770gain is working out of the box.
I'm not at my machine now, so this is from my head ;)

​

**Comment by bossanova808** [comment] 2015-04-07 09:51
Yep, here's the output
```
Inhuman Rampage
analyzing "Inhuman Rampage" ...
  [1/9] "01 Through The Fire And Flames.mp3": 
      integrated:  -7.5 LUFS / -10.5 LU
  [2/9] "02 Revolution Deathsquad.mp3": 
      integrated:  -6.9 LUFS / -11.1 LU
  [3/9] "03 Storming The Burning Fields.mp3": 
      integrated:  -7.0 LUFS / -11.0 LU
  [4/9] "04 Operation Ground And Pound.mp3": 
      integrated:  -7.3 LUFS / -10.7 LU
  [5/9] "05 Body Breakdown.mp3": 
      integrated:  -8.0 LUFS / -10.0 LU
  [6/9] "06 Cry For Eternity.mp3": 
      integrated:  -7.6 LUFS / -10.4 LU
  [7/9] "07 The Flame Of Youth.mp3": 
      integrated:  -7.8 LUFS / -10.2 LU
  [8/9] "08 Trail Of Broken Hearts.mp3": 
      integrated:  -8.6 LUFS / -9.4 LU
  [9/9] "09 Lost Souls In Endless Time (inhuman Rampage Special Edition) (Inhuman Rampage Special Edition).mp3": 
      integrated:  -7.6 LUFS / -10.4 LU
  [ALBUM]:
      integrated:  -7.5 LUFS / -10.5 LU
done.
```

**Comment by bossanova808** [comment] 2015-04-07 09:53
And another for good measure
```
MM
analyzing "MM" ...
  [1/15] "01 - Strangers To Ourselves.flac": 
      integrated:  -9.7 LUFS / -8.3 LU
  [2/15] "02 - Lampshades On Fire.flac": 
      integrated:  -7.6 LUFS / -10.4 LU
  [3/15] "03 - Shit In Your Cut.flac": 
      integrated:  -7.6 LUFS / -10.4 LU
  [4/15] "04 - Pistol (A. Cunanan, Miami, FL. 1996).flac": 
      integrated:  -8.0 LUFS / -10.0 LU
  [5/15] "05 - Ansel.flac": 
      integrated:  -7.7 LUFS / -10.3 LU
  [6/15] "06 - The Ground Walks, With Time In A Box.flac": 
      integrated:  -5.9 LUFS / -12.1 LU
  [7/15] "07 - Coyotes.flac": 
      integrated:  -8.3 LUFS / -9.7 LU
  [8/15] "08 - Pups To Dust.flac": 
      integrated:  -7.4 LUFS / -10.6 LU
  [9/15] "09 - Sugar Boats.flac": 
      integrated:  -6.3 LUFS / -11.7 LU
  [10/15] "10 - Wicked Campaign.flac": 
      integrated:  -7.4 LUFS / -10.6 LU
  [11/15] "11 - Be Brave.flac": 
      integrated:  -7.5 LUFS / -10.5 LU
  [12/15] "12 - God Is An Indian And You're An Asshole.flac": 
      integrated:  -10.2 LUFS / -7.8 LU
  [13/15] "13 - The Tortoise And The Tourist.flac": 
      integrated:  -6.5 LUFS / -11.5 LU
  [14/15] "14 - The Best Room.flac": 
      integrated:  -6.2 LUFS / -11.8 LU
  [15/15] "15 - Of Course We Know.flac": 
      integrated:  -7.4 LUFS / -10.6 LU
  [ALBUM]:
      integrated:  -7.2 LUFS / -10.8 LU
done.
```

**Comment by jmwatte** [comment] 2015-04-07 11:24
quickly between the soup and the potatoes...
If you get no other output on your commandline when importing (like:
analyzing this file...) then it seems to me that no items are getting to
the replaygain module.
If I look at the code it returns when there are no items to analyse and
then it goes to that error message you see

 return AlbumGain(output[-1], output[:-1])

​While still being away from my machine...
Have you tried it with another backend instead of the bs1770gain?
At least then we know that items are getting in the replaygain plugin ...

Back to my potatoes
;)

**Comment by jmwatte** [comment] 2015-04-07 13:08
FWIW : the albumgain part in

 replaygain:
    backend: bs1770gain
    overwrite: yes
    albumgain: yes

I can not find it mentioned when doing a search on this repository. 
So I think it is fair to say that  you can delete it. But best to check it with sampsyo.

I searched around and came to this:

Replaygain tags set but always 0 issue #628 
https://github.com/sampsyo/beets/issues/628

I wonder if those 2 issues are connected.


Anyway ...
Tomorrow I'll confiscate my daughters' windows machine and see if I can get beets working on that. In the mean time, I'll also put in some debuglines for some more info.

**Comment by sampsyo** [comment] 2015-04-07 14:01
@jmwatte Ah, cool. If that option is obsolete, would you mind removing it from the docs? Thanks!

**Comment by jmwatte** [comment] 2015-04-07 17:13
That's the question.... I haven't found it anywhere. It's not in the docs as far
as I can tell.



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.1.28&pv=4.4.2]

On di, apr. 07, 2015 at 4:01 PM, Adrian Sampson < notifications@github.com [notifications@github.com] > wrote:
@jmwatte [https://github.com/jmwatte] Ah, cool. If that option is obsolete, would you mind removing it from the docs?
Thanks!

—
Reply to this email directly or view it on GitHub
[https://github.com/sampsyo/beets/issues/1398#issuecomment-90567440] .[https://github.com/notifications/beacon/AAu4cEXZirWyCnHAsDVJfXRR5CIOyNQ0ks5n89qrgaJpZM4D7Udc.gif]

**Comment by sampsyo** [comment] 2015-04-07 18:54
Aha, great—yes, I think the option was removed. Thanks for checking.

**Comment by jmwatte** [comment] 2015-04-08 12:33
an update...

The primary reason that you have no output on windows has to do with
https://github.com/sampsyo/beets/issues/628
It's the prefix for filenames that exceed the MAX_PATH length that gets us into trouble.
That I can fix with something like:
 
    output = call(cmd + [syspath(i.path) for i in items])
        if not output :
            output = call(cmd + [syspath(i.path, prefix=False) for i in items])

That will get you into trouble with long filenames :(

I'm contacting the Peter Belkner to see if it is possible to make bs1770gain accept filenames with the prefix extension.
I'll keep you updated on that one.
But...
There is another problem now ...
Let me explain :
In linux the regex and parser work correct. In windows they don't.
this piece of code :
 
    regex = ("(\s{2,2}\[\d+\/\d+\].*?|\[ALBUM\].*?)(?=\s{2,2}\[\d+\/\d+\]"
                 "|\s{2,2}\[ALBUM\]:|done\.$)")
        results = re.findall(regex, data, re.S | re.M)

gives me the albumgain in linux, but in windows I don't get that one. So the program gives a replaygainerror because 'the tracks that go in' mismatch 'the items that come out'  with 1... :(

The file that Bsgain returns is the same in linux and windows :
.
analyzing "." ...
  [1/19] "01. Welcome To New York.mp3": 
      integrated:  -7.9 LUFS / -15.1 LU
  [2/19] "02. Blank Space.mp3": 
      integrated:  -8.3 LUFS / -14.7 LU
  [3/19] "03. Style.mp3": 
      integrated:  -7.5 LUFS / -15.5 LU
  [4/19] "04. Out Of The Woods.mp3": 
      integrated:  -9.1 LUFS / -13.9 LU
  [5/19] "05. All You Had To Do Was Stay.mp3": 
      integrated:  -7.8 LUFS / -15.2 LU
  [6/19] "06. Shake It Off.mp3": 
      integrated:  -8.2 LUFS / -14.8 LU
  [7/19] "07. I Wish You Would.mp3": 
      integrated:  -8.4 LUFS / -14.6 LU
  [8/19] "08. Bad Blood.mp3": 
      integrated:  -8.8 LUFS / -14.2 LU
  [9/19] "09. Wildest Dreams.mp3": 
      integrated:  -9.9 LUFS / -13.1 LU
  [10/19] "10. How You Get The Girl.mp3": 
      integrated:  -8.4 LUFS / -14.6 LU
  [11/19] "11. This Love.mp3": 
      integrated:  -9.0 LUFS / -14.0 LU
  [12/19] "12. I Know Places.mp3": 
      integrated:  -7.8 LUFS / -15.2 LU
  [13/19] "13. Clean.mp3": 
      integrated:  -9.9 LUFS / -13.1 LU
  [14/19] "14. Wonderland.mp3": 
      integrated:  -8.2 LUFS / -14.8 LU
  [15/19] "15. You Are In Love.mp3": 
      integrated:  -10.7 LUFS / -12.3 LU
  [16/19] "16. New Romantics.mp3": 
      integrated:  -7.8 LUFS / -15.2 LU
  [17/19] "17. I Know Places (Voice Memo).mp3": 
      integrated:  -19.4 LUFS / -3.6 LU
  [18/19] "18. I Wish You Would (Voice Memo).mp3": 
      integrated:  -18.4 LUFS / -4.6 LU
  [19/19] "19. Blank Space (Voice Memo).mp3": 
      integrated:  -17.9 LUFS / -5.1 LU
  [ALBUM]:
      integrated:  -9.2 LUFS / -13.8 LU
done.

Yeah, it's my daughters' windows machine ;)

The regex is the same.

It's just the [ALBUM]-part does not turn up in the results from regex.findall...
So I'm a bit stuck and am trying to get more info on that one...

**Comment by sampsyo** [comment] 2015-04-09 01:57
Wow; it's deeply disturbing that regex matching seems to differ on Windows vs. Linux. :scream:

@jmwatte, perhaps if we can narrow down a short string that shows off this match failing, we can start to understand how it's going wrong. If you paste the `repr()` version of that output string above, for example, maybe I can paste it into a Python interpreter here and see if I can reproduce the problem.

Nice T-Swift, BTW. :smiley:

**Comment by bossanova808** [comment] 2015-04-09 02:40
I am following but don't have a great deal to add here - happy to help if you need any outputs or whatever, and working on windows is tough...I have a windows machine running all the time

**Comment by jmwatte** [comment] 2015-04-09 10:38
T-Swift ... yeah... daughters' machine... I'm more of a T-Waits-er ;)
Anyway update...
Remember I never ran Beets on windows-machines.
So, almost everything is fixed. The regex is done... '\s' instead of 'b' ...
I build in some subroutines to make sure that when albums are really big I get no out-of-memory problems (splitting albums up in chuncks, settable in config)...

But now there is this...

    beet ls snoop check -p:
    C:\Users\myrthe\jm\test\Rap\Snoop Dogg\Doggystyle\17 CheckinÔÇÖ.1.mp3

If I run that through bs1770gain I get errors.
It goes through this routine

    try:
                output = call(cmd + [syspath(i.path) for i in items])
                if not output:
                    output = call(cmd + [syspath(i.path, prefix=False) for i in items])
    except:

So I thought these paths would be 'wellformed' ...but I'm probably forgetting something here...
Anyway I'll look into it but any help is appreciated...

**Comment by jmwatte** [comment] 2015-04-09 14:57
So...
I pushed a version. I checked it on linux and windows for the last hours with a lot of variations. It works as far as I can tell. 
To summarize(AFAICT):
* long path names are a windows/bs1770gain-problem. Best solution is support for long pathnames from bs1770gain.(waiting for an answer on that one)
* fix: throw the long-path prefix out of the window if the prefix does not work. 
  On the plus-side: it works for short filepaths. Down-side: long filepaths.
* Also on windows ...I ran into problems with some filenames(unicode?)...
*  fix: asciify_paths: true in the config.
Within those limitations it works.
So BossaNova ... maybe you can check it out. I may not be the perfect solution but till something better comes along...

**Comment by sampsyo** [comment] 2015-04-10 00:07
@jmwatte Since the tool currently can't handle the long-path prefix, shouldn't we just disable the prefix entirely for now? We can then bring it back if the tool starts to support it.

**Comment by jmwatte** [comment] 2015-04-10 05:32
Sure could do that. This was just to be save if they changed it without us
knowing. And when someone finds out they did I could just remove the "no-prefix"
condition.
What is your opinion on the asciify in the config ?



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.1.28&pv=4.4.2]

On vr, apr. 10, 2015 at 2:07 AM, Adrian Sampson < notifications@github.com [notifications@github.com] > wrote:
@jmwatte [https://github.com/jmwatte] Since the tool currently can't handle the long-path prefix, shouldn't we just
disable the prefix entirely for now? We can then bring it back if the tool
starts to support it.

—
Reply to this email directly or view it on GitHub
[https://github.com/sampsyo/beets/issues/1398#issuecomment-91385277] .[https://github.com/notifications/beacon/AAu4cEpmnnsVcu4gwEfLV096zCEaeR_Gks5n9wvDgaJpZM4D7Udc.gif]

**Comment by sampsyo** [comment] 2015-04-10 05:50
OK, good to know! Let's leave the fallback out for now (for simplicity) and add it back if something changes.

Recommending asciify_paths seems OK as a temporary workaround, since Python's handling of Unicode arguments to subprocesses on Windows is broken. (See also similar issues with convert and chroma, via audioread).

**Comment by jmwatte** [comment] 2015-04-10 05:53
Ok will do..



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.1.28&pv=4.4.2]

On vr, apr. 10, 2015 at 7:50 AM, Adrian Sampson < notifications@github.com [notifications@github.com] > wrote:
OK, good to know! Let's leave the fallback out for now (for simplicity) and add
it back if something changes.

Recommending asciify_paths seems OK as a temporary workaround, since Python's
handling of Unicode arguments to subprocesses on Windows is broken. (See also
similar issues with convert and chroma, via audioread).

—
Reply to this email directly or view it on GitHub
[https://github.com/sampsyo/beets/issues/1398#issuecomment-91437997] .[https://github.com/notifications/beacon/AAu4cGhBhQCs8uI1AAQu72POgEGps-cIks5n91wbgaJpZM4D7Udc.gif]

**Comment by sampsyo** [comment] 2015-04-10 16:02
Great; thanks. I implemented a few other small cleanups.

@bossanova808 Can you confirm that this works—or at least does not crash—on your machine now?

**Closed** 2015-04-10 16:01 UTC
Labels: bug, replaygain

**Comment by bossanova808** [comment] 2015-04-11 01:02
I will be able to try tomorrow maybe...sorry got caught up by some dental surgery :(

**Comment by sampsyo** [comment] 2015-04-11 01:09
No hurry! Dental surgery sounds much more important.

**Comment by bossanova808** [comment] 2015-04-13 01:23
(Much less pleasant anyway).

Ok I tried running from source on two albums.  
C:\GIT\beets>beet version
beets version 1.3.12
plugins: chroma, embedart, fetchart, ftintitle, lyrics, missing, replaygain, scrub

No crash, but no replaygain tags in the output either?

Config section is simply:
```
replaygain:
    backend: bs1770gain
    overwrite: yes
```

bs1770gain.exe is in my path

Any ideas??

**Comment by sampsyo** [comment] 2015-04-13 01:32
Got the verbose output from running the replaygain command?

**Comment by bossanova808** [comment] 2015-04-13 01:56
As in manually?  I see no output about RG running beets anymore...

```
f:\Unsorted\Music\Inhuman Rampage (9 items)
Correcting tags from:
    Dragonforce - Inhuman Rampage (Special Edition)
To:
    DragonForce - Inhuman Rampage
URL:
    http://musicbrainz.org/release/2f5489f2-edc4-3e36-9dae-8298c254e29a
(Similarity: 96.9%) (album, year, tracks) (CD, 2005, JP)
 * Through The Fire And Flames (#0) ->
   Through the Fire and Flames (#1)
 * Revolution Deathsquad (#0) ->
   Revolution Deathsquad (#2)
 * Storming The Burning Fields (#0) ->
   Storming the Burning Fields (#3)
 * Operation Ground And Pound (#0) ->
   Operation Ground and Pound (#4)
 * Body Breakdown (#0) ->
   Body Breakdown (#5)
 * Cry For Eternity (#0) ->
   Cry for Eternity (#6)
 * The Flame Of Youth (#0) ->
   The Flame of Youth (#7)
 * Trail Of Broken Hearts (#0) ->
   Trail of Broken Hearts (#8)
 * Lost Souls In Endless Time (inhuman Rampage Special Edition) (Inhuman Rampage
 Special Edition) (#0) ->
   Lost Souls in Endless Time (#9) (title)

f:\Unsorted\Music>
```

Sample output from running the Rg manually is above...

**Comment by sampsyo** [comment] 2015-04-13 02:12
Yes, with the non-import RG command, but in verbose mode:

    $ beet -v replaygain

**Comment by bossanova808** [comment] 2015-04-13 03:04
Ok so then I do get output. Although it's happening on the unprocessed files that were imported, not the copied files in the output directory 

```
F:\Unsorted\Music>beet -v replaygain
user configuration: C:\Users\X\AppData\Roaming\beets\config.yaml
data directory: C:\Users\X\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
library database: C:\Utilities\beets\library.db
library directory: F:\TestOut
Sending event: library_opened
replaygain: analyzing Doves - The Places Between: The Best Of - There Goes the Fear
Sending event: database_change
Sending event: write
Sending event: after_write
replaygain: analyzing Doves - The Places Between: The Best Of - Black And White Town
Sending event: database_change
Sending event: write
Sending event: after_write
replaygain: analyzing Doves - The Places Between: The Best Of - Snowden
Sending event: database_change
Sending event: write
Sending event: after_write
````

Just an explanation - at the moment before really getting in to beets, I am using it on my downloads/mess folder and output the processed files (via copy) to TestOut...rather than working with my actual final library...until such a time as I know it's all working well.

So my *expectation* is that all the processing happens on the initial import (including RG) - and the output files go in to TestOut and are added to my beets library.  At the moment I then manually copy them over to my master library once I have checked them, all separate from beets, and have been manually doing replaygain on those as a last step (this was the main missing thing for me).

Periodically I have been doing a beets up to get rid of things now absent from my downloads folder and that I've moved from TestOut to my master library - so my beets library remains basically empty and I am just using it as a processor.

Anyway - am I misunderstanding here?  Should it not be doing RG on input?

**Comment by sampsyo** [comment] 2015-04-13 03:19
You're not misunderstanding. That should work. I just asked you to run the explicit command so we could see the debugging output.

That all looks OK; no indication that anything's amiss. There are really no RG tags written?

**Comment by bossanova808** [comment] 2015-04-13 03:25
Definitely not - I inspect with mp3tag and have a custom columns for replaygain that works will all replaygain outs I have seen - the column is empty.  I have also used it to inspect all extended tags and they're not there.  Checked an mp3 album and a flac one.

(and I **can** see the output from the ones being processed in the source folder itself)

**Comment by sampsyo** [comment] 2015-04-13 03:34
How about with `beet info` (a plugin you may need to enable)? Does that show the values for the imported files?

**Comment by bossanova808** [comment] 2015-04-13 03:47
It does not

**Comment by sampsyo** [comment] 2015-04-13 04:11
How strange. Since the tool is reporting success, I'm not sure what else to suggest. Please post again if you discover any evidence about what could be going wrong.

**Comment by bossanova808** [comment] 2015-04-13 04:28
hmm, so I got rid of everything from both the in and out folder

beet up - deletes a bunch of stuff
beet info - shows nothing
beet import -v Whatever
beet import  -v Whatever2

imports successfully, outputs to the TestOut folder, but definitely no RG tags and no output about it either.

beet -v replaygain

Processes Whatever and Whatever2 in the TestOut folder and adds the tags.

So basically it just appears to be not running RG at all now on import. It was before, but crashed, so something in these changes seems to mean it is bailing earlier...

**Comment by sampsyo** [comment] 2015-04-13 05:16
> So basically it just appears to be not running RG at all now on import. It was before, but crashed, so something in these changes seems to mean it is bailing earlier...

Wow; that's quite strange. Thanks for investigating. Is there anything suspicious in the verbose (`-vv`) output during import?

> beet info - shows nothing

This command is used with a path.

**Comment by bossanova808** [comment] 2015-04-13 05:38
Nothing in -vv that I can see, no reference to replaygain at all (can see others, chroma, lyrics, scrubbing etc).

I do notice if RG tags exists in a file they are not removed.

**Comment by sampsyo** [comment] 2015-04-13 06:02
Aha, thanks! It looks like there was a bug that was preventing debug output from the plugin in import mode. Can you give the latest few commits a try and see if `beet -vv import ...` is any more helpful now?

**Comment by bossanova808** [comment] 2015-04-13 06:27
ok progress 

```
replaygain: analyzing DragonForce - Inhuman Rampage
replaygain: executing bs1770gain --replaygain -it F:\Unsorted\Music\Inhuman Rampage\01 Through The Fire And Flames.mp3 F:\Unsorted\Music\Inhuman Rampage\02 Revo
lution Deathsquad.mp3 F:\Unsorted\Music\Inhuman Rampage\03 Storming The Burning Fields.mp3 F:\Unsorted\Music\Inhuman Rampage\04 Operation Ground And Pound.mp3 F
:\Unsorted\Music\Inhuman Rampage\05 Body Breakdown.mp3 F:\Unsorted\Music\Inhuman Rampage\06 Cry For Eternity.mp3 F:\Unsorted\Music\Inhuman Rampage\07 The Flame
Of Youth.mp3 F:\Unsorted\Music\Inhuman Rampage\08 Trail Of Broken Hearts.mp3 F:\Unsorted\Music\Inhuman Rampage\09 Lost Souls In Endless Time (inhuman Rampage Sp
ecial Edition) (Inhuman Rampage Special Edition).mp3
replaygain: analysis finished: analyzing ...
  [1/9] "01 Through The Fire And Flames.mp3":
      integrated:  -7.5 LUFS / -10.5 LU
       true peak:  0.9 TPFS / 1.105080
  [2/9] "02 Revolution Deathsqua        1%
      integrated:  -6.9 LUFS / -11.1 LU
       true peak:  0.7 TPFS / 1.080454
  [3/9] "03 Storming The Burning Fields.mp3":
      integrated:  -7.0 LUFS / -11.0 LU
       true peak:  1.1 TPFS / 1.137201
  [4/9] "04 Operation Ground And Pound.mp3":
      integrated:  -7.3 LUFS / -10.7 LU
       true peak:  0.7 TPFS / 1.084129
  [5/9] "05 Body Breakdown.mp3":
      integrated:  -8.0 LUFS / -10.0 LU
       true peak:  0.9 TPFS / 1.112334
  [6/9] "06 Cry For Etern        1%1%
      integrated:  -7.6 LUFS / -10.4 LU
       true peak:  0.7 TPFS / 1.082500
  [7/9] "07 The Flame Of Youth.mp3":
      integrated:  -7.8 LUFS / -10.2 LU
       true peak:  0.7 TPFS / 1.086795
  [8/9] "08 Trail Of Broken Heart        1%
      integrated:  -8.6 LUFS / -9.4 LU
       true peak:  0.6 TPFS / 1.067787
  [9/9] "09 Lost Souls In Endless Time (inhuman Rampage Special Edition) (Inhuman Rampage Special Edition).mp3":
      integrated:  -7.6 LUFS / -10.4 LU
       true peak:  0.6 TPFS / 1.077090
  [ALBUM]:
      integrated:  -7.5 LUFS / -10.5 LU
       true peak:  1.1 TPFS / 1.137201
done.

replaygain: 9 items, 9 results
replaygain: ReplayGain error: ReplayGain backend failed for some tracks in album DragonForce - Inhuman Rampage
Sending event: item_copied
```

Looks like there is still some issues with paths maybe?
(I am using the asciify_paths option)

**Comment by jmwatte** [comment] 2015-04-13 08:10
Goodmorning,
Been busy I see.
I think I know what is causing the problem.
I split up the long regex on multiple lines and then it doesn't get the last album tag. 9 items 9 results should be 10 results. I just wished I could split it up correctly. I am out now for a few hours but I'll try again when I get back. Sorry for that. But I'm sure it works I just tested it. It's the split regex...aaaahhhhhh

**Comment by jmwatte** [comment] 2015-04-13 08:50
I fixed it. It's tested. I pushed it. If it gets through, try it. Got to go. Back in a few hours.

**Comment by bossanova808** [comment] 2015-04-13 09:40
Yep one quick test here works!  Yay!

Will report back again after some more testing

**Comment by bossanova808** [comment] 2015-04-13 10:24
Yep seems to work ok.  The asciify paths thing is a shame to have to use (I actually use unicode in python win regularly without issue - learnt from - http://blog.notdot.net/2010/07/Getting-unicode-right-in-Python

But 4 albums processed successfully with RG.

**Comment by sampsyo** [comment] 2015-04-13 15:33
Woohoo! Thanks, @jmwatte. And thanks to @bossanova808 for testing.

The remaining issue is not Unicode in general but a bug in Python with calling subprocesses on Windows with Unicode arguments: http://bugs.python.org/issue1759845
