### ISSUE TITLE
Allow paths stored in databse to be relative

### ISSUE THREAD

**Issue by Phydaw-Hawk** [beetbox/beets#2736] opened 2017-11-09 09:00 UTC
Hi,
First, please, excuse me for my bad English.
I would like to propose to have paths stored in database to be relative, and not absolute like now.
As there is an option, in YAML configuration file, which define the directory where files are stored, all paths stored in database begin with this directory, obviously.
Is it possible to have another option that says the paths stored in database are relative to the path defined by the 'directory' option.
The aim is if we want/have to move all files in another place (disk crash or whatever ...), we have only to change directory option in the configuration file, nothing else.
Currently, to do that, we have to update all fields in the database with the new path, with sql sentences for example, in addition to change the directory option.
I looked in issues to find if this feature exists, and I did not find.
So, if it exists, don't blame ;-)) But, tell me how to do that, please.
Thanks for reading, and of course, for this very useful tool.

**Comment by Vrihub** [comment] 2017-11-09 09:37
Hi, I'm interested in this too. There's already an issue discussing this: see #133

**Comment by Phydaw-Hawk** [comment] 2017-11-09 12:40
Thanks, Vrihub.
I looked for that by many weeks, and you founded it in less than hour ...
As the request already exists, perhaps may have to close mine, to not have the same subject in many issues ?

**Comment by sampsyo** [comment] 2017-11-09 14:02
Indeed; thanks! Closing as a duplicate of #133.

**Closed by sampsyo** 2017-11-09 14:02 UTC
