### ISSUE TITLE
Some albums don't have an albumartist_sort

### ISSUE THREAD

**Issue by dosoe** [beetbox/beets#2559] opened 2017-05-13 15:07 UTC
### Problem

Running this command in verbose (`-vv`) mode gives:

[dorian@stonearch Sat May 13 ~]$ -> beet -vv info /media/windows/Users/Dorian/Musik/beets/_/250th\ Anniversary\ Edition_\ Symphonies/03-19\ Les\ petits\ riens\,\ KV\ 299b_\ XIII.\ Gavotte.mp3 
user configuration: /home/dorian/.config/beets/config.yaml
data directory: /home/dorian/.config/beets
plugin paths: 
Sending event: pluginload
library database: /media/windows/Users/Dorian/Musik/beets/library.db
library directory: /media/windows/Users/Dorian/Musik/beets
Sending event: library_opened
/media/windows/Users/Dorian/Musik/beets/_/250th Anniversary Edition_ Symphonies/03-19 Les petits riens, KV 299b_ XIII. Gavotte.mp3
      acoustid_id: d4dcf291-9670-4082-af0a-561933b01a0e
            album: 250th Anniversary Edition: Symphonies
      albumartist: Wolfgang Amadeus Mozart; Royal Concertgebouw Orchestra, Nikolaus Harnoncourt, Amsterdam Baroque Orchestra, Ton Koopman
      albumstatus: official
        albumtype: album
              art: True
           artist: Wolfgang Amadeus Mozart
      artist_sort: Mozart, Wolfgang Amadeus
             asin: B000AOVKH8
         bitdepth: 0
          bitrate: 320083
       catalognum: 2564 62334-2
         channels: 2
          country: US
             date: 2006-01-10
              day: 10
             disc: 3
        disctitle: Six German Dances, Les petits riens, Symphonies nos. 25, 26
        disctotal: 8
           format: MP3
            genre: Classical
           genres: Classical
            label: Warner Classics
           length: 218.01333333333332
 mb_albumartistid: b972f589-fb0e-474e-b64a-803b0364fa75
       mb_albumid: eea51aa8-bead-497a-8d22-5f4a20000b44
      mb_artistid: b972f589-fb0e-474e-b64a-803b0364fa75
mb_releasegroupid: 8be36646-28db-3a1a-98d8-da36880cf45f
       mb_trackid: 72ab640c-cd2d-4a5c-9bd9-1ac89b042eae
            media: CD
            month: 1
    original_date: 2006-01-10
     original_day: 10
   original_month: 1
    original_year: 2006
       samplerate: 44100
           script: Latn
            title: Les petits riens, KV 299b: XIII. Gavotte
            track: 19
       tracktotal: 26
             year: 2006
Sending event: cli_exit

Strangely, there is no albumartist_sort tag (even if there is an albumartist). This problem affects a few albums, but only a minority of my collection. 
Concerned albums are: 
https://musicbrainz.org/release/eea51aa8-bead-497a-8d22-5f4a20000b44
https://musicbrainz.org/release/cdb2a397-4684-4ff2-bfdd-3f8c2d95caa4
https://musicbrainz.org/release/eedbf924-14f2-4707-aeef-4e8856cb3ef0
among others. 
I can upload files upon request. 

### Setup

* OS: Arch Linux
* Python version: 3.6.1
* beets version: git-latest (updated the same day)
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:
[dorian@stonearch Sat May 13 ~]$ -> beet config
directory: /media/windows/Users/Dorian/Musik/beets
library: /media/windows/Users/Dorian/Musik/beets/library.db

import:
    copy: no
    write: yes
    incremental: no

plugins: inline web duplicates info fetchart mbsync the badfiles
badfiles:
    commands:
        ogg: ogginfo -q

paths:
    default: '%asciify{$albumartist_sort}/%asciify{$album}/$disc-$track %asciify{$title}'
    singleton: ZZZ_Non-Album/%ifdef{composer_sort,%asciify{$composer_sort},no composer}/%asciify{$artist_sort}/%asciify{$title}
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    reverse_proxy: no
    include_paths: no
the:
    the: yes
    a: yes
    format: '{0}, {1}'
    strip: no
    patterns: []
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    store_source: no
pathfields: {}
item_fields: {}
album_fields: {}
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''

**Comment by sampsyo** [comment] 2017-05-13 15:28
Hi! This is probably because MusicBrainz doesn't have a sort name for the given artist. To help debug what's going on, you could try printing out the MusicBrainz web service response, which has the full data for a release, and comparing one that gives you a sort name with one that doesn't.

**Comment by dosoe** [comment] 2017-05-13 15:32
The third release has only Johann Sebastian Bach as an artist, I have other releases where they recognize him fine. How can I print out the MB web service response?

**Comment by dosoe** [comment] 2017-05-13 15:58
It's pretty wierd, beets update /directory gives (among others)
Sending event: database_change
Pyotr Ilyich Tchaikovsky - Symphonies nos. 4, 5 & 6 "Pathétique" - Symphony no. 6 in B minor, op. 74 "Pathétique": II. Allegro con grazia
  albumartist: Pyotr Ilyich Tchaikovsky; Berlin Philharmonic Orchestra, Herbert von Karajan -> Wiener Philharmoniker
  albumartist_sort:  -> Tchaikovsky, Pyotr Ilyich; Berlin Philharmonic Orchestra, Karajan, Herbert von
  genre: Symphonic -> Classical
  albumtype: album -> 
  language:  -> zxx
  albumstatus: official -> 
Sending event: database_change
and beet info for the same file gives: 

[dorian@stonearch Sat May 13 ~]$ -> beet info /media/windows/Users/Dorian/Musik/beets/_/Symphonies\ nos.\ 4\,\ 5\ \&\ 6\ _Pathetique_/02-04\ Symphony\ no.\ 6\ in\ B\ minor\,\ op.\ 74\ _Pathetique__\ II.\ Allegro\ con\ grazia.ogg 
/media/windows/Users/Dorian/Musik/beets/_/Symphonies nos. 4, 5 & 6 _Pathetique_/02-04 Symphony no. 6 in B minor, op. 74 _Pathetique__ II. Allegro con grazia.ogg
      acoustid_id: e84583fc-e7bc-48f1-a3e7-e5b80ea03c21
            album: Symphonies nos. 4, 5 & 6 "Pathétique"
      albumartist: Wiener Philharmoniker
 albumartist_sort: Tchaikovsky, Pyotr Ilyich; Berlin Philharmonic Orchestra, Karajan, Herbert von
              art: True
           artist: Pyotr Ilyich Tchaikovsky
      artist_sort: Tchaikovsky, Pyotr Ilyich
             asin: B000001GYJ
         bitdepth: 0
          bitrate: 320000
       catalognum: 453 089-2
         channels: 2
         composer: Пётр Ильич Чайковский
          country: US
             date: 1997-07-15
              day: 15
             disc: 2
        disctotal: 2
          encoder: MediaMonkey 4.0.7
           format: OGG
            genre: Classical
           genres: Classical
            label: Deutsche Grammophon
         language: zxx
           length: 534.0
 mb_albumartistid: 9ddd7abc-9e1b-471d-8031-583bc6bc8be9
       mb_albumid: e25eb366-4c08-407c-bb5b-6d7887e0153a
      mb_artistid: 9ddd7abc-9e1b-471d-8031-583bc6bc8be9
mb_releasegroupid: f8ca1c1c-9102-3bfa-8a4a-e021ce8d2320
       mb_trackid: be79a21e-3b16-4841-8518-1c9097f3dd8e
            media: CD
            month: 7
    original_date: 1997-04-01
     original_day: 1
   original_month: 4
    original_year: 1997
       samplerate: 44100
           script: Latn
            title: Symphony no. 6 in B minor, op. 74 "Pathétique": II. Allegro con grazia
            track: 4
       tracktotal: 6
             year: 1997

but "beet move" doesn't move anything even if  my path default is: 
paths:
default: '%asciify{$albumartist_sort}/%asciify{$album}/$disc-$track %asciify{$title}'
Right now he is in '_' (with all the albums with no albumartist_sort). 
It seems beet move doesn't see that there is an akbumartist_sort now.

**Comment by sampsyo** [comment] 2017-05-13 23:27
(I edited your comment to surround terminal pastes in ```.)

That's odd! I'm not sure how to reproduce this. Maybe you can provide your database file along with instructions, or show how to get into the same situation "from scratch"?

**Comment by dosoe** [comment] 2017-05-14 12:41
So my workflow is the following: 
tag using MusicBrainz Picard
beet import
beet update
beet mbsync
beet move 
(beet dup -m and delete dupes if necessary)

This problem appears only with a small subset of my collection ( 637 out of the 25000 I have on my laptop, 17 releases). 
Skipping beet mbsync doesn't change anything. 
For some of them beet info doesn't give an "albumartist_sort", for some it does. All have an "albumartist", and for all of them Musicbrainz does have an "albumartist_sort", at least on musicbrainz.org. 
The list of the concerned albums: 
Bedřich Smetana; Czech Philharmonic Orchestra, Rafael Kubelík - My Country
Felix Mendelssohn; Claudio Abbado, London Symphony Orchestra - 5 Symphonies / 7 Overtures
Franz Liszt; Claudio Arrau, Nikita Magaloff - The Complete Etudes
Hector Berlioz; Sir Colin Davis - Complete Orchestral Works
Jean Sibelius; Hallé Orchestra, Sir John Barbirolli - Complete Symphonies / Orchestral Works
Johann Sebastian Bach - Bach 2000: The Complete Bach Edition, Volume 12: The Orchestral Works
Johann Sebastian Bach; Gustav Leonhardt - Gustav Leonhardt Plays Bach: Goldberg Variations / The Well-Tempered Clavier / The Art of the Fugue / Sonatas for Violin and Harpsichord / Organ Works
Johann Strauss II, Josef Strauss; Berlin Philharmonic Orchestra, Herbert von Karajan - Radetzky-Marsch
Johannes Brahms; Arcanto Quartet, Silke Avenhaus - String Quartet, op. 51 no.1 / Piano Quintet, op. 34
Johannes Brahms; Pražák Quartet, Ivan Klánský - Piano Quintet Op 34 / String Quartet No 3 Op 67
Maurice Duruflé; Corydon Singers, English Chamber Orchestra, Matthew Best - Requiem / Four Motets
Pyotr Ilyich Tchaikovsky; Berlin Philharmonic Orchestra, Herbert von Karajan - Symphonies nos. 4, 5 & 6 "Pathétique"
Richard Strauss; Staatskapelle Dresden, Rudolf Kempe - Orchestral Works
Robert Schumann; Claire Désert - Davidsbundlertanze Op.6 - Intermezzi Op.4
Tomaso Giovanni Albinoni, Joseph Haydn, Johann Nepomuk Hummel; Håkan Hardenberger - Famous Classical Trumpet Concertos
Wolfgang Amadeus Mozart; Frans Brüggen, Eric Hoeprich, Orchestra of the Eighteenth Century - Clarinet Concerto / Clarinet Quintet
Wolfgang Amadeus Mozart; Royal Concertgebouw Orchestra, Nikolaus Harnoncourt, Amsterdam Baroque Orchestra, Ton Koopman - 250th Anniversary Edition: Symphonies

I noticed that all the files do not have an albumartist_sort when I hit "beet update", but do have one when I hit "beet mbsync". For whatever reason, hitting "beet move" after "beet mbsync" now does move the files. I don't even try to understand that, maybe there was a problem somewhere. However, it would be interesting to find out why some files don't get an albumartist_sort.

**Comment by sampsyo** [comment] 2017-05-14 15:05
OK! I agree it would be interesting to get to the bottom of this, but to do that, I'll need to reproduce the problem "from scratch" (i.e., starting from a completely empty library) without too much configuration. Let us know if you find a way to do that.

**Comment by dosoe** [comment] 2017-05-14 15:37
I hope it's not reproduceable, that means my problem is gone. I'm checking around with my music on the harddisk.

**Comment by dosoe** [comment] 2017-05-15 09:35
Ok that's what 'beet mbsync' and 'beet info' give: 

```
[dorian@stonearch Mon May 15 ~]$ -> beet mbsync /run/media/dorian/41715435-89cb-4e8e-b531-40708180c365/Musique/beets/_/
.
.
.
albumartist: Wolfgang Amadeus Mozart; Hermann Prey, Edith Mathis, Gundula Janowitz, Dietrich Fischer-Dieskau, Tatiana Troyanos, Chor der Deutschen Oper Berlin und Orchester der Deutschen Oper Berlin, Karl Böhm -> Wolfgang Amadeus Mozart; Hermann Prey, Edith Mathis, Gundula Janowitz, Dietrich Fischer‐Dieskau, Tatiana Troyanos, Chor der Deutschen Oper Berlin und Orchester der Deutschen Oper Berlin, Karl Böhm
  albumartist_sort:  -> Mozart, Wolfgang Amadeus; Prey, Hermann, Mathis, Edith, Janowitz, Gundula, Fischer‐Dieskau, Dietrich, Troyanos, Tatiana, Chor der Deutschen Oper Berlin und Orchester der Deutschen Oper Berlin, Böhm, Karl
  albumartist_credit:  -> Mozart; Hermann Prey, Edith Mathis, Gundula Janowitz, Dietrich Fischer‐Dieskau, Tatiana Troyanos, Chor und Orchester der Deutschen Oper Berlin, Karl Böhm
  language:  -> ita
  albumstatus: official -> Official
[dorian@stonearch Mon May 15 ~]$ -> beet info -l /run/media/dorian/41715435-89cb-4e8e-b531-40708180c365/Musique/beets/_/Le\ nozze\ di\ Figaro/01-01\ Le\ nozze\ di\ Figaro\,\ K.\ 492_\ Sinfonia.mp3 
/run/media/dorian/41715435-89cb-4e8e-b531-40708180c365/Musique/beets/_/Le nozze di Figaro/01-01 Le nozze di Figaro, K. 492_ Sinfonia.mp3
acoustid_fingerprint: 
         acoustid_id: 4c35bcc0-3da6-47f3-832c-797e9ab16d6f
               added: 2017-04-30 14:25:39
               album: Le nozze di Figaro
            album_id: 1426
         albumartist: Wolfgang Amadeus Mozart; Hermann Prey, Edith Mathis, Gundula Janowitz, Dietrich Fischer-Dieskau, Tatiana Troyanos, Chor der Deutschen Oper Berlin und Orchester der Deutschen Oper Berlin, Karl Böhm
  albumartist_credit: 
    albumartist_sort: 
```
It doesn't really make sense to me. 
Importing the files again in a new empty library removed the problem, for whatever reason. 
Reimporting the files in the initial library removed it as well. 
I don't understand what's happening, I don't want to understand since it works now but maybe you are interested.

**Comment by sampsyo** [comment] 2017-05-15 14:45
Ah; that's weird—so running `beet mbsync` repeatedly finds the same "problem" that needs to be "fixed," even though it purports to have applied the fix the first time around?

**Comment by dosoe** [comment] 2017-05-15 20:17
yes, pretty much. And running it multiple times solves the problem. It seems to be unstable though: importing the files again seems to solve this.

**Comment by sampsyo** [comment] 2017-05-16 15:40
Very strange. Well, I'll need to close this for now without a way to get into the same state—but let us know if there's a way to recreate the problem from scratch.

**Closed by sampsyo** 2017-05-16 15:40 UTC
Labels: needinfo

**Comment by Freso** [comment] 2017-05-16 15:52
> This is probably because MusicBrainz doesn't have a sort name for the given artist.

FWIW, it's not possible for a MusicBrainz artist to not have a sort name, so this should never be the cause.

**Comment by dosoe** [comment] 2017-06-14 11:38
Ok the problem keeps reappearing: when I make '''beet update && beet mbsync && beet move''' then some albums loose their albumartist_sort. If I reimport them, they get it back. 2 albums that consistently get this problem: https://musicbrainz.org/release/7cb9b8b7-e682-482e-b361-72749b1f8363 and https://musicbrainz.org/release/28fec9aa-7efc-4661-b3f5-9cc8c7d991c2 . What kind of output could I get you to help finding the problem?

**Comment by sampsyo** [comment] 2017-06-14 14:33
That's odd. What we really need, as usual, is a way to reproduce the problem "from scratch": with a neutral configuration, and an empty library, what should someone do to observe the disappearing albumartist_sort?

Specifically, the place to start narrowing it down would be to know which of those three commands is the problem. (I'm guessing it's `update`?) And, I suppose, to check whether the problem persists if you have as little in your configuration as possible.

**Comment by SimonHova** [comment] 2018-03-18 18:24
I hate to revive an old issue, but I'm getting the same thing with two Ace of Base releases. The albumartist_sort field doesn't come over until I mbsync a few times.

**Comment by sampsyo** [comment] 2018-03-18 18:57
If you’re having trouble on the latest version, please file a new bug with complete details and instructions for how to reproduce the problem.

**Comment by dosoe** [comment] 2018-03-19 15:46
I think I kinda found out what created the problem: if you imported the data and never did a ```beet write``` he might be still using the data written on the file, which has never been updated. If you do a ```beet up``` and then ```beet write``` it doesn't change anything. Does this problem still appear if you do ```beet mbsync && beet write```?
