### ISSUE TITLE
`beet update` messes up albumtype tags under Bash for Windows

### ISSUE THREAD

**Issue by light** [beetbox/beets#4938] opened 2023-10-07 14:11 UTC
### Problem

Running `beet update` inside Git Bash under Windows 10, albumtype and albumtypes are split into single letters :

```sh
$ beet update
Some Artist - Some Album - Some Song
  albumtype: soundtrack -> a
  albumtypes: album; soundtrack -> ['a', 'l', 'b', 'u', 'm', ';', ' ', 's', 'o', 'u', 'n', 'd', 't', 'r', 'a', 'c', 'k']
```

Under PowerShell, I get the same behavior :

```sh
PS C:\Users\light> beet update
Some Artist - Some Album - Some Song
  albumtypes: album; soundtrack -> ←[31;01m['←[39;49;00ma←[31;01m', '←[39;49;00ml←[31;01m', '←[39;49;00mb←[31;01m', '←[39;49;00mu←[31;01m', '←[39;49;00mm←[31;01m', '←[39;49;00m;←[31;01m',←[39;49;00m ←[31;01m' ', '←[39;49;00ms←[31;01m', '←[39;49;00mo←[31;01m', '←[39;49;00mu←[31;01m', '←[39;49;00mn←[31;01m', '←[39;49;00md←[31;01m', '←[39;49;00mt←[31;01m', '←[39;49;00mr←[31;01m', '←[39;49;00ma←[31;01m', '←[39;49;00mc←[31;01m', '←[39;49;00mk←[31;01m']←[39;49;00m
  albumtype: ←[31;01msoundtr←[39;49;00ma←[31;01mck←[39;49;00m -> a
```

Under `cmd`, I don't see this behavior :

```sh
C:\Users\light>beet update

C:\Users\light>
```

Using cmd however is not really viable since there is no color support and escape sequences are displayed bare (as in PowerShell). Which seems related to that other issue : https://github.com/beetbox/beets/issues/2607

### Setup

Completely fresh install of beet and basic config, first thing I imported.

```sh
$ beet --version
beets version 1.6.0
Python version 3.9.1
no plugins loaded
```
```sh
$ beet config
directory: M:/MP3/sorted
library: M:/MP3/musiclibrary.db

import:
    move: yes
```

**Comment by arsaboo** [comment] 2023-10-12 21:56
I am seeing this in Ubuntu too. Looks like it happens only with `album; soundtrack` (need to double check this)

```bash
Some Artist - Some Album - Some Song
  albumtype: soundtrack -> a
  albumtypes: album; soundtrack -> a; l; b; u; m; ;;  ; s; o; u; n; d; t; r; a; c; k
```

**Comment by pioneerHitesh** [comment] 2023-10-14 12:54
@arsaboo i would like to pick this issue up can you assign this to me?

**Comment by arsaboo** [comment] 2023-10-14 13:12
@pioneerHitesh Absolutely... please submit a PR. There is no assignment on beets, but anyone working on this will see your comment.

**Comment by pioneerHitesh** [comment] 2023-10-15 07:05
> I am seeing this in Ubuntu too. Looks like it happens only with `album; soundtrack` (need to double check this)
> 
> ```shell
> Some Artist - Some Album - Some Song
>   albumtype: soundtrack -> a
>   albumtypes: album; soundtrack -> a; l; b; u; m; ;;  ; s; o; u; n; d; t; r; a; c; k
> ```



> I am seeing this in Ubuntu too. Looks like it happens only with `album; soundtrack` (need to double check this)
> 
> ```shell
> Some Artist - Some Album - Some Song
>   albumtype: soundtrack -> a
>   albumtypes: album; soundtrack -> a; l; b; u; m; ;;  ; s; o; u; n; d; t; r; a; c; k
> ```
This issue is not reproducible on ubuntu shell does your album name contain any special characters?

**Comment by pioneerHitesh** [comment] 2023-10-15 09:47
@light @arsaboo this issue is not reproducible on windows 11 powershell and git bash.

**Comment by arsaboo** [comment] 2023-10-15 15:04
Here's one:
```
Sukhwinder Singh & Sunidhi Chauhan - Billu Barber - Marjaani (Electro House)
  albumtypes: album; soundtrack -> a; l; b; u; m; ;;  ; s; o; u; n; d; t; r; a; c; k
  albumtype: album -> a
```

**Comment by pioneerHitesh** [comment] 2023-10-15 15:47
@arsaboo  ok will look into it

**Comment by pioneerHitesh** [comment] 2023-10-15 16:10
@arsaboo does it happen on ubuntu terminal?

**Comment by arsaboo** [comment] 2023-10-21 14:06
This is excessive:
```
arsaboo@arsplex:~$ beet info album:"ALBUM"
        albumtype: s
       albumtypes: s; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; i; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; n; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; g; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; l; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; e

```

@sampsyo any thoughts what may be driving it...I am lost here and not sure what/how to fix this.

**Comment by sampsyo** [comment] 2023-10-21 19:52
Unfortunately this seems to require some very careful debugging, and I don't have an immediate intuition about the source. I would start with #4582, which purports to have addressed this general issue—and start by ensuring that everyone experiencing it is using a version of the code with that fix?

**Comment by JOJ0** [comment] 2023-10-29 10:07
@light as sampsyo suggested: Please try to replicate this issue with the current beets version in development (git master). Thanks!

**Comment by JOJ0** [comment] 2023-10-29 10:11
@pioneerHitesh if you want to pick up this issue, please read #4582 as sampsyo suggested, then read https://github.com/beetbox/beets/issues/4715 which describes, as far as I understood it, the part of the initial issue that _remains to be fixed_

**Comment by pioneerHitesh** [comment] 2023-10-29 10:14
@JOJ0 will take a look at this and will give it another try.

**Comment by arsaboo** [comment] 2023-11-01 14:00
Weirdly enough, I am now seeing some going in the reverse direction after I updated. 
```
  albumtypes: a; ;;  ; l; ;;  ; b; ;;  ; u; ;;  ; m -> album
  albumtype: a -> album
```

**Comment by JOJ0** [comment] 2023-11-01 20:50
> Weirdly enough, I am now seeing some going in the reverse direction after I updated. 
> 
> ```
> 
>   albumtypes: a; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; l; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; b; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; u; ;;  ; ;; ;;  ;  ; ;;  ; ;; ;;  ; ;; ;;  ;  ; ;;  ;  ; ;;  ; ;; ;;  ;  ; ;;  ; m -> album
> 
>   albumtype: a -> album
> 
> ```

Yep, we still haven't fixed this issue. I'm sure you remember ;-)

Happens if you have broken data in the db already.
Here's how to temporarily fix it: https://github.com/beetbox/beets/pull/4582#issuecomment-1445023493

**Comment by Gremious** [comment] 2023-11-22 14:45
Just wanted to say that this also happened to me on latest (? - 1.6.0) on debian bullseye. I don't think OS matters here.

Brand new user, started importing my library, 1 artist folder at a time. After 3-4, I ran `beet update` to try and fix something, and it happened to me not with soundtrack, but with `album; compilation`  as well as with just `album` and `ep`.

I already did the `beet write` for the fix but I do see it the output of what it fixed:
```
D3Δ†H H3X - Arcana - PΔRΔMΦUR
  albumtype: a -> album
  albumtypes: ['a', 'l', 'b', 'u', 'm'] -> album

D3Δ†H H3X - King Remixes - King (NOIRE ANTIDOTE remix)
  albumtype: e -> ep
  albumtypes: ['e', 'p'] -> ep

Darkside - Take a Trip, Part 1 - Trumphession
  albumtype: a -> compilation
  albumtypes: ['a', 'l', 'b', 'u', 'm', ';', ' ', 'c', 'o', 'm', 'p', 'i', 'l', 'a', 't', 'i', 'o', 'n'] -> album; compilation
```

So seemingly, it's any os, and any albumtype

**Comment by JOJ0** [comment] 2023-11-22 21:49
@Gremious sorry you got i to this. It's partly fixed in git latest beets version. Please upgrade and try fix your library using the steps described here https://github.com/beetbox/beets/issues/4938#issuecomment-1789661336

**Comment by Gremious** [comment] 2023-11-22 22:04
Yep it's alright, I did that fix just earlier, all is well :)

Good to know it's actually fixed on latest, I will use git version, thanks for the heads up!

**Comment by JOJ0** [comment] 2023-12-10 11:46
Duplicate of https://github.com/beetbox/beets/issues/4528

**Closed** 2023-12-10 11:47 UTC
Labels: needinfo, update command
