### ISSUE TITLE
Invalid syntax error launching beets after PIP install

### ISSUE THREAD

**Issue by dannn-o** [beetbox/beets#3157] opened 2019-02-21 03:15 UTC
I've been running beets (latest version) under Linux Mint 18.x for several years, and I recently switched over to Mint 19.1.  To get beets installed under 19.1, these are the commands I ran:
```
sudo apt-get install python-dev python-pip
sudo apt-get install python3-setuptools
sudo apt-get install python-setuptools
sudo pip install beets
```
Afterward, I copied over my /.config/beets/ folder from my 18.3 machine to the 19.1 build.  However, whenever I try to launch beets from the command line, I'm getting the following error:

```
~$ beet config
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 42, in <module>
    from beets.autotag import mb
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/__init__.py", line 26, in <module>
    from .match import tag_item, tag_album, Proposal  # noqa
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/match.py", line 24, in <module>
    from munkres import Munkres
  File "/usr/local/lib/python2.7/dist-packages/munkres.py", line 79
    def pad_matrix(self, matrix: Matrix, pad_value: int=0) -> Matrix:
                               ^
SyntaxError: invalid syntax
```

 I have a feeling something is out of sorts with the version of Python, even though the 
messages above seem to indicate version 2.7 is being run (which beets docs say is supported).
Checking /usr/bin shows both Python 2.7.15rc1 and Python 3.6.7 available.  Any suggestions are appreciated.

**Comment by jackwilsdon** [comment] 2019-02-21 03:17
Duplicate of #3154 - see #3146.

I don't think we've mastered a release containing the fix for this yet, so you'll have to run the [latest source version of beets](https://beets.readthedocs.io/en/v1.4.7/faq.html?highlight=git#run-the-latest-source-version-of-beets) until a new release has been created.

**Closed by jackwilsdon** 2019-02-21 03:17 UTC

**Comment by dannn-o** [comment] 2019-02-21 03:24
Thanks for the prompt response, and sorry I didn't catch the existing issue (I did do a search beforehand).  I will follow your suggestions of installing the latest source version.
