### ISSUE TITLE
"beet missing" crashes due to potential problem with DB data

### ISSUE THREAD

**Issue by maffo999** [beetbox/beets#4035] opened 2021-08-27 05:04 UTC
**Problem**
Running "beet missing" on my setup crashes with "IndexError: list index out of range", while running "beet missing -a" completes successfully
The following backtrace is provided with the crash
```
Traceback (most recent call last):
  File "/usr/bin/beet", line 33, in <module>
    sys.exit(load_entry_point('beets==1.5.0', 'console_scripts', 'beet')())
  File "/usr/lib/python3.9/site-packages/beets/ui/__init__.py", line 1291, in main
    _raw_main(args)
  File "/usr/lib/python3.9/site-packages/beets/ui/__init__.py", line 1278, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.9/site-packages/beetsplug/missing.py", line 126, in _miss
    helper(lib, decargs(args))
  File "/usr/lib/python3.9/site-packages/beetsplug/missing.py", line 155, in _missing_tracks
    for item in self._missing(album):
  File "/usr/lib/python3.9/site-packages/beetsplug/missing.py", line 219, in _missing
    if len(list(album.items())) < album.albumtotal:
  File "/usr/lib/python3.9/site-packages/beets/dbcore/db.py", line 489, in __getattr__
    return self[key]
  File "/usr/lib/python3.9/site-packages/beets/dbcore/db.py", line 396, in __getitem__
    return self._get(key, raise_=True)
  File "/usr/lib/python3.9/site-packages/beets/dbcore/db.py", line 377, in _get
    return getters[key](self)
  File "/usr/lib/python3.9/site-packages/beets/library.py", line 1240, in _albumtotal
    return self.items()[0].tracktotal
  File "/usr/lib/python3.9/site-packages/beets/dbcore/db.py", line 796, in __getitem__
    return self._objects[n]
IndexError: list index out of range
```

Running "beet -vvv missing" reveals some albums to have a wrong MusicBrainzID but this happens multiple times before the crash so I don't believe it to be relevant, e.g.:
```
Requesting MusicBrainz release 5800479
Invalid MBID (5800479).
```

**Setup**
- OS: Arch Linux
- Python version: 3.9.6
- beets version: 1.5.0
- plugins: badfiles, discogs, duplicates, edit, embedart, fetchart, inline, kodiupdate, lyrics, missing, subsonicupdate
- Turning off plugins made problem go away (yes/no): disabling every other plugin except for "missing" causes no change in behavior

I believe one album in my collection might have something odd with the number/amount of tracks in the DB and this is causing the missing plugin to fail: I would appreciate if someone could help me find it and fix it.

**Comment by maffo999** [comment] 2021-08-28 09:47
You're absolutely right:
```
[user@home ~]$ sqlite3 .config/beets/beets.db "select album,id from albums where id not in (select album_id from items);"
...Не гони лошадей!|1751
[user@home ~]$ sqlite3 .config/beets/beets.db "select * from items where album_id = 1751;"
[user@home ~]$ 
```
After removing the album with ID 1751 from the `albums` table `beets missing` works again.
On how this could have happened in the first place, the only plausible explanation I have is that the files/folder associated with the album have been manually deleted.
I find however strange that `beet update` didn't catch it and automatically removed the album from the DB once the files have gone missing.

**Comment by sampsyo** [comment] 2021-08-28 14:03
Well, glad it's cleared up, but too bad about the mystery! Do comment again if the problem crops up again and maybe we can root-cause it.

**Comment by wisp3rwind** [comment] 2021-10-04 19:34
Closing this, since we're probably not going to figure out anymore what the root cause was. Feel free to re-open if there's an idea what it might have been.

**Closed by wisp3rwind** 2021-10-04 19:34 UTC
Labels: needinfo, missing
