### ISSUE TITLE
Broken pipe on piping `list` output on Python 3

### ISSUE THREAD

**Issue by Azphreal** [beetbox/beets#2622] opened 2017-07-05 11:01 UTC
### Problem

I'm trying to write a quick dirty script to play the first result of a search, looking much like you'd expect:

```sh
mpv --no-audio-display "$(beet ls -p $@ | head -n 1)"
```

However, there's something in the formatting of the output that `head` doesn't like:

```sh
$ beet ls -p home
/media/beets/5 Seconds of Summer/5 Seconds of Summer/09 Long Way Home.mp3
/media/beets/5 Seconds of Summer/LIVESOS/07 Long Way Home.mp3
/media/beets/5 Seconds of Summer/Sounds Good Feels Good/12 Broken Home.mp3
/media/beets/American Authors/What We Live For/07 Go Big or Go Home.mp3
/media/beets/Boys Like Girls/Crazy World/09 Take Me Home.mp3
...
```

However

```sh
beet -vv ls -p home | head -n 1                                                                                                                                                                   user configuration: /home/shagaru/.config/beets/config.yaml
data directory: /home/shagaru/.config/beets
plugin paths: 
Sending event: pluginload
library database: /media/Music/library.db
library directory: /media/Music
Sending event: library_opened
/media/beets/5 Seconds of Summer/5 Seconds of Summer/09 Long Way Home.mp3
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

```

Trying to cheat and run it through `echo` instead produces the following:

```sh
$ echo -e $(beet ls -p home) | head -n 1
/media/beets/5 Seconds of Summer/5 Seconds of Summer/09 Long Way Home.mp3 /media/beets/5 Seconds of Summer/LIVESOS/07 Long Way Home.mp3 /media/beets/5 Seconds of Summer/Sounds Good Feels Good/12 Broken Home.mp3 /media/beets/American Authors/What We Live For/07 Go Big or Go Home.mp3 /media/beets/Boys Like Girls/Crazy World/09 Take Me Home.mp3 ...
```

as one string, so it seems like the proper line-ending characters aren't being properly generated. This may be expected of Python output, I don't know; I haven't written using it.

End question I suppose is there any way around how Python handles printing lines short of rewriting that entire part of the program?

### Setup

* OS: GNU/Linux
* Python version: 3.5.2
* beets version: 1.4.4
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) shouldn't matter, because it's a question of how the program functions inherently.

**Comment by sampsyo** [comment] 2017-07-05 14:55
Thank you! I can reproduce this, and it looks like it's a new problem on Python 3. We actually have a [specific exception handler](https://github.com/beetbox/beets/blob/6185c6ad4ba689ed438c2075699eb12b24ef5daf/beets/ui/__init__.py#L1276-L1279) for closed pipes on Python 2, but the same technique apparently doesn't work on Python 3. I don't fully understand what's going on with the "Exception ignored" mechanism… some further digging is required here.

**Comment by nathdwek** [comment] 2017-07-12 09:54
Reading https://stackoverflow.com/a/26738736, and testing it, it seems replacing  `pass` in the linked snippet with sys.stderr.close() solves this issue.

I don't know if it could hide useful information in the future though. I think it won't since this is for a very specific errno.

**Comment by sampsyo** [comment] 2017-07-12 17:16
Huh! Wow! Thanks for looking into it—this isn't precisely what I expected, but it makes sense. I suppose the problem is that just ignoring the exception caused some sort of internal exception handler to trigger, which can't produce anything because the output streams are already shutting down. Closing the pipe avoids that.

This does indeed looks like the right fix; let's do it! :sparkles:

I believe an extra flush should probably be unnecessary—each write we do to stderr should be followed by a flush already. For example, the main thing we do is call `logging` to write lines to stderr; that flushes after every logging call. I could be proven wrong, but I think we're fine to just close.

**Closed** 2017-07-22 08:49 UTC
Labels: bug, python 3
