### ISSUE TITLE
Crash on startup: ValueError: Name node can't be used with 'None' constant

### ISSUE THREAD

**Issue by Alsciende** [beetbox/beets#3683] opened 2020-07-23 17:12 UTC
Here is the traceback

```
$ beet -v
no user configuration found at /Users/cedric/.config/beets/config.yaml
data directory: /Users/cedric/.config/beets
plugin paths: 
Sending event: pluginload
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
```

First, I installed beets on MacOS with python 2.7 installed and linked from Homebrew. I also installed pylast and discogs-client. Everything worked wonderfully, except for the warning messages about using Python 3.

I'm not proficient at Python, at all. I installed and linked python 3.8 (`brew link --overwrite python@3`) and tried to launch beets. It couldn't be found anymore, since the Python version had changed. I installed beets and the 2 plugins again. But whenever I try to start it, it crashes with that traceback.

What I tried:
- revert to python@2, but it crashed in the exact same way
- uninstall beets and its 2 plugins from both version of Python
- unlink both version of Python, then link python@3 properly
- rename my config folder to make sure it wasn't causing the issue

**Comment by jackwilsdon** [comment] 2020-07-23 19:34
Duplicate of #3674.

**Closed by jackwilsdon** 2020-07-23 19:34 UTC
