### ISSUE TITLE
beet import hangs very often

### ISSUE THREAD

**Issue by l-t-k** [beetbox/beets#1701] opened 2015-11-05 14:19 UTC
My setup: 
Windows Server 2012 with a harddisk formatted as NTFS.
The disk is served to an Ubuntu Server 14.04 Machine with SAMBA. Both machines are virtual.
Beets version 1.15

Ran several tests, many of them are stuck on (random tracks) the writing event:
`Sending event: write`. 
At that point, nothing happens anymore, even if I leave it running for days. The problem does only occur if autotagging is enabled. It happens mostly on imports with large album(s) (> 20 track or 2 or more discs). If I import files with move and autotagging enabled and the new and old location differ the importer hangs leaving some files in the new location and some files in the old location.
Tried several config files, with simple path formatting and without any plugins, move enabled and disabled. None of these solved anything.
Checked the files that were stuck with a windows program to see if they were 'locked': they were not.
The only thing I can conclude from everything I have tested so far is that the importer hangs on the write event when it's trying to write metadata to files.
Any idea what the problem can be?

**Comment by sampsyo** [comment] 2015-11-06 01:12
Sorry about the trouble. It's really hard to diagnose network filesystems—but they can definitely be flaky! By default, we have to blame Samba: beets doesn't do anything special with its file writes, so there's nothing else obvious to guess.

If you can somehow get together a test case we can reproduce, maybe we can try to narrow down what's going wrong on your setup.

**Comment by kooimens** [comment] 2015-11-06 20:13
Thanks for the response. Changed from Samba to NFS. Each test running ends up with this error:
`Error: No such file or directory while moving /mnt/wd1/files/TESTimport/[V.A.] Hitzone/[1998] TMF Hitzone 3/111 Eagle-Eye Cherry - Save Tonight.mp3 to /mnt/wd1/files/TESTmusic/musicbrainz/[V.A.] Hitzone/[1998] TMF Hitzone 3/111 Eagle-Eye Cherry - Save Tonight.mp3`

`Error: No such file or directory while moving /mnt/wd1/files/TESTimport/[V.A.] Hitzone/[1998] TMF Hitzone_ Best of '98/108 Run-D.M.C. vs. Jason Nevins - It's Like That.mp3 to /mnt/wd1/files/TESTmusic/musicbrainz/[V.A.] Hitzone/[1998] TMF Hitzone_ Best of '98/108 Run-D.M.C. vs. Jason Nevins - It's Like That.mp3`

`Error: No such file or directory while moving /mnt/wd1/files/TESTimport/[V.A.] Hitzone/[1999] TMF Hitzone 6/104 Tarkan - Simarik.mp3 to /mnt/wd1/files/TESTmusic/musicbrainz/[V.A.] Hitzone/[1999] TMF Hitzone 6/104 Tarkan - Simarik.mp3`

The file is still there in the old location (not in the new one). I can't write/delete it within Ubuntu. If I switch to my windows box, I can delete the file and there seems to be no problems exist at all.

**Comment by kooimens** [comment] 2015-11-06 20:42
Looks like something goes wrong when naming the paths. No errors if I copy instead of move the files on auto import: (for the above examples)
`111 Eagleâ€Eye Cherry - Save Tonight`
`101 Runâ€D.M.C. vs. Jason Nevins - It's Like That`
`104 Tarkan - ÅžÄ±marÄ±k`

**Comment by kooimens** [comment] 2015-11-06 21:24
Any idea why it's renamed from Eagle-Eye to Eagleâ€�Eye Cherry?

**Comment by sampsyo** [comment] 2015-11-06 21:34
Looks like a filesystem encoding issue—another weird vagary that can arise with network filesystems. You may be able to get this right by tweaking your system's locale settings.

**Comment by kooimens** [comment] 2015-11-06 21:52
On the ubuntu server:
`LANG="en_US.UTF-8"
LANGUAGE="en_US:en"`

Beets keeps renaming - to â€�. Even if i'm just working locally (not using any network share).

**Comment by sampsyo** [comment] 2015-11-06 22:01
There's always also a chance that the display (i.e., terminal emulator settings) are to blame. These encoding problems are incredibly tricky to diagnose!

**Comment by sampsyo** [comment] 2016-01-26 18:57
Since we can't nail down what's happening here, I'm closing this issue. Please reopen it if there's new actionable information.

**Closed by sampsyo** 2016-01-26 18:57 UTC
Labels: needinfo, import command
