### ISSUE TITLE
how does Lastgenere can't get genre for Taylor Swift's 1989?

### ISSUE THREAD

**Issue by medyagh** [beetbox/beets#1786] opened 2015-12-31 16:51 UTC
I tried to fetch the genre using album and track, and it fetches genre for most of my library except Taylor Swift 1989 ? could it because She has put some different copyright on it ?

**Comment by sampsyo** [comment] 2015-12-31 18:51
Can you please provide more detail about what's happening so that we can try to reproduce the problem? Here are some resources on how to report bugs effectively:

* [The beets FAQ](http://docs.beets.io/en/v1.3.16/faq.html#report-a-bug-in-beets). See the points about including your configuration and narrowing down the problem so we can observe it here too.
* [This "grading rubric"](http://adriansampson.net/blog/bugrubric.html), which explains what makes a bug report useful in general.

**Comment by sampsyo** [comment] 2016-02-01 01:54
Closing due to timeout. Please reopen if you can give instructions to reproduce the problem.

**Closed by sampsyo** 2016-02-01 01:54 UTC
Labels: needinfo
