### ISSUE TITLE
Album merging/completion

### ISSUE THREAD

**Issue by ghost** [beetbox/beets#112] opened 2013-02-28 19:40 UTC
This issue was automatically migrated from Google Code.
_Original author: zent...@gmail.com (April 29, 2012 18:26:17)_
_Original issue: https://github.com/google-code-export/beets/issues/380_

**Comment by pedros** [comment] 2015-05-25 16:57
Just came across this issue. This is addressed in 3be593693d3f7f60eb07e8445ec669fe9ce84c68, at the duplicates plugin level (so, not within the importer). Might still be of use, though.

**Comment by bartkl** [comment] 2016-05-19 07:14
From what I'm reading I can imagine the `edit' plugin might come in handy in the process of (optionally?) applying some final tidying edits after the merge (if chosen) since this might have undesired consequences as far as the consistency of tags is concerned.

If that sounds useful to you guys it should probably become a new issue, but for now it's only a thought.

**Comment by nomadturk** [comment] 2016-06-08 18:22
Any news on this?

I'ld like to see this feature on beets. This is a must-have kinda feature I think.
For example I have this partial album with tracks 1, 3, 7 and 8 but the rest are missing.
And let's say I have another partial album on an different directory with tracks 1, 2, 3, 4, 9, 10, 11.
Whilst importing if beets were to pickup the missing tracks (and maybe check for quality and replace the better one) then I'ld end up with 1, 2, 3, 4, 7, 8, 9, 10, 11.
Now tracks 5 and 6 seem to be still missing but that would be OK. This still is better than having less.

Currently if I have even 1 track beets skip it saying I already have the album. So maybe adding an Import Missing tracks feature would be wise as well.

**Comment by sampsyo** [comment] 2016-06-08 18:39
If you're interested in a feature, please consider helping implement it!

**Comment by sean-abbott** [comment] 2017-02-02 17:35
Also, with regard to @nomadturk's comment:

Let's say that an album is supposed to have 6 tracks.
If I have 1, 3, and 5 currently, and I import 4, 5, and 6, then a resolution needs to do two things.

First, it has to merge the tracks that only exist in one or the other sets, so 1, 3, 4, and 6, I DEFINITELY want to keep.

After that, though, I'd want to compare 5.  Are they different bit rates? Is one a better musicbrainz match?  Different lengths?

So I'd want merge resolution to be two stage: union the album as a whole, and then deal with duplicate tracks individually.

**Comment by sampsyo** [comment] 2017-02-02 18:46
The way this would work according to the current proposal is to reuse the existing importer logic. That means both sets of tracks would get thrown together into one big basket, and that would then be re-tagged as the same album.

If you have duplicate tracks, then the "best" one will be picked according to match similarity. Interactively resolving track duplicates would be the purview of something like #154.

**Comment by sean-abbott** [comment] 2017-02-02 19:25
Personally, I'd rather NOT automate the "best" pick...

And edit, a la #154 is not the goal...being able to make a track-by-track-non edit comparison and choose one, the other, or both is preferable.

**Comment by sampsyo** [comment] 2017-02-02 19:31
Right. I'm just saying that manually choosing resolutions like this is actually orthogonal: it can come up in ordinary imports too if you happen to have too many tracks in a folder.

We actually have the "edit option" for editing metadata. (See the `edit` plugin.) The reason I bring up #154 is because the original intention there was changing the order (i.e., the matching) of tracks, which would also require dealing with unmatched/duplicate tracks.

**Comment by sean-abbott** [comment] 2017-02-02 19:41
Gotcha, ok.

**Comment by xerg0n** [comment] 2017-04-03 12:16
Hi, has any progess been made on this feature? I would be willing to help/implement it, but i dont want to do duplicate work or step on any toes. Thanks in advance

**Comment by udiboy1209** [comment] 2017-04-03 12:55
I had tried a few things, but none were particularly useful. Also it was three years ago and the codebase may have changed a lot since then... So you start afresh for this feature.

**Comment by xerg0n** [comment] 2017-04-03 16:35
Thanks for the advance. This will be my first beets plugin, so it may take some time but i will start working on it in the next few days.

**Closed** 2017-11-11 16:08 UTC
Labels: feature, migrated

**Comment by intelfx** [comment] 2017-11-11 20:08
Incredible!

**Comment by dosoe** [comment] 2018-03-08 12:04
I'm wondering: how about release groups? They also appear in MusicBrainz and group albums that are basically reissues of one another (stuff like Harmonia Mundi Gold). Could it be possible to extend what has just been implemented with releases to release groups? In many cases you do not want to have a duplicate of the music just because one is the original version of 1987 and the other one is the reissue of 2010 because now it is a legendary recording or because one wants to make money again with it (I'm throwing numbers at random, but there are countless examples). Some people might prefer to keep them separate for the sake of completeness, but I believe this is a minority. So far what I did was to use ```beet dup``` and set the ```mb_releasegroupid``` as a key but it is not very satisfying because the album gets sometimes cut into two complementary folders. I don't know if it is a problem many people experience, but it seems to be quite similar to merging albums.

**Comment by dosoe** [comment] 2018-03-08 12:04
And thanks for the awesome work!

**Comment by mkirkland4874** [comment] 2018-09-17 23:58
With “merge all”, it appears that if you attempt to import a song that is already in the album you are merging, beets will rename the song to a totally different song randomly and incorrectly. You will think you have a song when in fact it is a duplicate of another song.

For example:

**Step 1:** Import Track 01 and 02 of Album A (which has 5 songs total). Beets imports the two songs into one album correctly.
**Step 2:** Import Track 03 of Album A. Beets offers you the “merge all” option to combine with the 2 songs imported in Step 1. Beets correctly imports Track 03 and combines it into Album A created in Step 1. There are now 3 of 5 songs of Album A in the library.
**Step 3:** Import Tracks 03 and 04 (note 03 is already in the library and 04 is new). Beets offers you the “merge all” option. **You select “merge all” and beets renames the Track 03 you are importing to Track 05 incorrectly and imports track 04 correctly.** Now beets thinks you have a complete Album of all 5 songs in Album A, when in fact songs 03 and 05 are the same song.

**Comment by laker-93** [comment] 2024-12-13 21:23
Is this issue really closed? I still don't see a way to merge albums in to a single directory. `beet duplicates --merge` won't work unless there are duplicates but you can end up in a following scenario where there are no duplicates but beets has decided to put tracks in to different directories (due to importing the album piecemeal)

```
root@4787cef4963b:/# beet ls Skee -p
/music/Skee Mask/C [111]/07 - Minitx.mp3
/music/Skee Mask/C [112]/09 - Blok.mp3
/music/Skee Mask/C [110]/10 - Pitchacid.mp3
/music/Skee Mask/C [111]/11 - thnk u.mp3
```

Is there a command to merge these all in to the same album?

**Comment by JOJ0** [comment] 2024-12-18 20:50
You can try reimporting by passing the paths to the files then select the same album each time and select the appropriate merge option.

merge has to be enabled in the config of course - or passed via cli argument.

**Comment by laker-93** [comment] 2024-12-26 11:49
@JOJ0  - thanks for the information. I think that would indeed work for my use case. Another thought is that this could be solvable as a one liner using the `duplicates` plugin. If I execute `beet duplicates -a` in my above situation, it would print out `Skee Mask - C` as it has detected the duplicate at the album level. If one could put the duplicates plugin in 'album mode' and then instruct it to merge, with for example `beet duplicates -a --merge`, then that would solve my use case without having to fiddle around with reconfiguring `duplicate_action`. Does this sound reasonable? If so, I'd be willing to look at implementing such a feature.

**Comment by laker-93** [comment] 2024-12-26 13:34
What I'm trying to achieve here is to import the tracks piecemeal and end up with all tracks being placed in a common directory:
`/music/Skee Mask/C/`

An alternative perhaps simpler solution is to set the album id of all tracks to the same with something like:

`beet mod album_id=<album-id>`

however doing so would then change the path of all tracks to:

`/music/Skee Mask/C [album-id]/`

which is still not ideal!

**Comment by laker-93** [comment] 2024-12-26 18:57
I've just removed the `aunique` disambiguator from the path format which seems to have solved my use case.
