### ISSUE TITLE
unknown characters in windows command line

### ISSUE THREAD

**Issue by Esteidinger** [beetbox/beets#3212] opened 2019-04-09 17:50 UTC
### Problem
I have having a problem with how beets displays its questions in windows command line. 

5. Bob Marley - Greatest Hits ([31;01m18.5%[39;49;00m) [33;01m(missing tracks, artist, tracks, ...)[39;49;00m [37m(CD, 1996, XE, Citadel)[39;49;00m
# selection (default [36;01m1[39;49;00m), [34;01mS[39;49;00mkip, [34;01mU[39;49;00mse as-is, as [34;01mT[39;49;00mracks, [34;01mG[39;49;00mroup albums,
[34;01mE[39;49;00mnter search, enter [34;01mI[39;49;00md, a[34;01mB[39;49;00mort?

Running this command in verbose (`-vv`) mode:

C:\Users\Steid>beet -vv
user configuration: C:\Users\Steid\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Steid\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
library database: W:\PlexMedia\Music\musiclibrary.db
library directory: W:\PlexMedia\Music\Cleaned Music
Sending event: library_opened
Usage:

* OS:  Windows 10
* Python version:  3.7.3

**Comment by jackwilsdon** [comment] 2019-04-09 17:55
Duplicate of #2607

**Closed by jackwilsdon** 2019-04-09 17:55 UTC
