### ISSUE TITLE
Encoding error on linux (Debian)

### ISSUE THREAD

**Issue by JulienPivard** [beetbox/beets#1954] opened 2016-04-25 13:36 UTC
### Problem

At random time beet stop on traceback error.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import *
```

Led to this problem:

```
Evaluating 5 candidates.
Candidate: Hoobastank - The Reason
Success. Distance: 0.01
Candidate: Hoobastank - Is This The Day?
Success. Distance: 0.53
Candidate: Hoobastank - The Reason
Success. Distance: 0.04
Candidate: Hoobastank - The Reason
Success. Distance: 0.49
Candidate: Hoobastank - The Reason
Success. Distance: 0.02
Sending event: import_task_start
Looking up: /home/asmodee/Musique/Musique/Melanie/HoosBastank - crawling in the dark
Tagging Hoobastank - Hoobastank
No album IDs found.
Search terms: Hoobastank - Hoobastank
Album might be VA: False
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Evaluating 5 candidates.
Candidate: Hoobastank - Hoobastank
Success. Distance: 0.15
Candidate: Hoobastank - Hoobastank
Success. Distance: 0.14
Candidate: Hoobastank - Hoobastank
Success. Distance: 0.18
Candidate: Hoobastank - Hoobastank
Success. Distance: 0.19
Candidate: Hoobastank - Hoobastank
Success. Distance: 0.17
Sending event: import_task_start
Looking up: /home/asmodee/Musique/Musique/Melanie/Nymphetamine
Tagging Cradle Of Filth - Nymphetamine
No album IDs found.
Search terms: Cradle Of Filth - Nymphetamine
Album might be VA: False
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Sending event: albuminfo_received
Evaluating 5 candidates.
Candidate: Cradle of Filth - Nymphetamine
Success. Distance: 0.12
Candidate: Cradle of Filth - Nymphetamine
Success. Distance: 0.12
Candidate: Cradle of Filth - Nymphetamine
Success. Distance: 0.02
Candidate: Cradle of Filth - Nymphetamine
Success. Distance: 0.02
Candidate: Cradle of Filth - Nymphetamine
Success. Distance: 0.02

Sending event: import_task_choice
Sending event: import_task_apply
0 of 11 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.17', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1236, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1226, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 966, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 943, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 321, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 252, in run
    msg = self.coro.next()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1203, in read_tasks
    for t in task_factory.tasks():
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1048, in tasks
    tasks = self._create(self.album(paths, dirs))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1127, in album
    items = map(self.read_item, paths)
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1177, in read_item
    return library.Item.from_path(path)
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 505, in from_path
    i.read(path)
  File "/usr/local/lib/python2.7/dist-packages/beets/library.py", line 562, in read
    value = getattr(mediafile, key)
  File "/usr/local/lib/python2.7/dist-packages/beets/mediafile.py", line 1082, in __get__
    out = style.get(mediafile.mgfile)
  File "/usr/local/lib/python2.7/dist-packages/beets/mediafile.py", line 555, in get
    return _sc_decode(data)[self.index]
  File "/usr/local/lib/python2.7/dist-packages/beets/mediafile.py", line 220, in _sc_decode
    soundcheck = soundcheck.replace(b' ', b'').decode('hex')
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
```

### Setup

* OS:  linux debian
* Python version: Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
* beets version: beets version 1.3.17
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/Beets/Musique/

import:
    move: no
    copy: yes
library: ~/Beets/baseDeDonneeMusiqueBeets.blb

```

**Comment by jackwilsdon** [comment] 2016-04-25 14:35
The unicode string for `\xe9` is an accented e - `é`. I guess we are trying to parse it as ASCII when it's actually UTF-8?

**Comment by JulienPivard** [comment] 2016-04-25 14:48
It's a Windows file (Desktop.ini or Thumbs.ini) that created the issue. I deleted it and it solved the problem. Unfortunately I didn't think of looking at the encoding.

**Comment by jackwilsdon** [comment] 2016-04-25 15:07
Interesting, I guess that's due to `*` including the `desktop.ini` (or non-audio file) and beets attempting to read it's tags?

**Comment by JulienPivard** [comment] 2016-04-25 15:51
Yes that's what I figured out

**Comment by sampsyo** [comment] 2016-04-25 17:55
Hi! I think this is likely #1895, which has been fixed on master. Any chance you could give the latest source a try?

**Comment by JulienPivard** [comment] 2016-04-30 16:55
I have the latest version. Command 
```sh
sudo pip install -U beets
```
return already up-to-date for each line.

**Comment by sampsyo** [comment] 2016-04-30 17:08
Sorry, I meant the latest unreleased source. The FAQ has instructions.

**Comment by JulienPivard** [comment] 2016-04-30 17:40
I can't try with the latest source, sorry.
The file Desktop.ini that created the issue has been deleted.

**Comment by jackwilsdon** [comment] 2016-04-30 17:42
If you can't try out the latest version, you'll sadly have to wait until 1.3.18 is released.

**Comment by jrobeson** [comment] 2016-09-24 21:24
@JulienPivard :  I'm pretty sure this is fixed, so I'm going to close it.  Feel free to reopen if you can still reproduce after the next beets release.

**Closed by jrobeson** 2016-09-24 21:24 UTC
Labels: needinfo
