### ISSUE TITLE
Runtime failure

### ISSUE THREAD

**Issue by bengadbois** [beetbox/beets#1798] opened 2016-01-05 00:02 UTC
Sorry for not having a better title. Not sure where it stems from.

```
$ beet import Dennis\ Sheperd\ -\ Fight\ Your\ Fears\ \(2015\)\ \{WEB\}\ \[FLAC\]/
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1140, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1130, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 875, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 852, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1246, in lookup_candidates
    task.lookup_candidates()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 583, in lookup_candidates
    autotag.tag_album(self.items)
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/match.py", line 433, in tag_album
    search_album, va_likely)
  File "/usr/local/lib/python2.7/dist-packages/beets/autotag/hooks.py", line 567, in album_candidates
    out.extend(plugins.candidates(items, artist, album, va_likely))
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 356, in candidates
    out.extend(plugin.candidates(items, artist, album, va_likely))
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/discogs.py", line 145, in candidates
    return self.get_albums(query)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/discogs.py", line 205, in get_albums
    type='release').page(1)
  File "/usr/local/lib/python2.7/dist-packages/discogs_client/models.py", line 347, in page
    data = self.client._get(self._url_for_page(index))
  File "/usr/local/lib/python2.7/dist-packages/discogs_client/client.py", line 123, in _get
    return self._request('GET', url)
  File "/usr/local/lib/python2.7/dist-packages/discogs_client/client.py", line 110, in _request
    content, status_code = self._fetcher.fetch(self, method, url, data=data, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/discogs_client/fetchers.py", line 95, in fetch
    resp = request(method, uri, headers=headers, data=body)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 562, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 145, in connect
    match_hostname(self.sock.getpeercert(),
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 313, in getpeercert
    for value in get_subj_alt_name(x509)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 94, in get_subj_alt_name
    asn1Spec=general_names)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 825, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 391, in valueDecoder
    r.verifySizeSpec()
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 251, in verifySizeSpec
    def verifySizeSpec(self): self._sizeSpec(self)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/constraint.py", line 32, in __call__
    '%s failed at: \"%s\"' % (self, sys.exc_info()[1])
pyasn1.type.error.ValueConstraintError: ConstraintsIntersection(ConstraintsIntersection(), ValueSizeConstraint(1, 64)) failed at: "ValueSizeConstraint(1, 64) failed at: "SubjectAltName().setComponents(GeneralName(componentType=NamedTypes(NamedType('otherName', Anot
herName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5S
tring(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet(()
, Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('
registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('f.ssl.fastly.net', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(N
amedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagCla
ss=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, t
agId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<
no value>')))).setComponents(None, None, IA5String('*.500px.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<
no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), Named
Type('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceI
dentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None
, IA5String('*.adis.ws', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagS
et=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((
), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), T
ag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.adroll.com', tagSet=TagSet
((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFor
mat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagI
d=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)
))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.beacon.fastlydns.net', tagSet=TagSet((), Tag(tagClass=128, tagFo
rmat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet
=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('director
yName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', 
OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.beatport.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(com
ponentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFor
mat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedType
s(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(ta
gClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.britishcouncil.org', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedTyp
e('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType
('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())
), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId
=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.businessinsider.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(co
mponentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagS
et=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagC
lass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registered
ID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.catchpoint.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('
type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, ta
gFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4))))
, NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>'
)))).setComponents(None, None, IA5String('*.cooladata.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no val
ue>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('
dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentif
ier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5S
tring('*.discogs.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet
=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((),
 Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag
(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.disq.us', tagSet=TagSet((), 
Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=3
2, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))
)), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), 
NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.dotabuff.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId
=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), T
ag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(
componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(t
agSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.e3expo.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=Name
dTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0
)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('',
 RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tag
Format=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.fastly-debug.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', An
otherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA
5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet(
(), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType
('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('*.format-assets.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTy
pes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(t
agClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tag
...
It goes on and on and ends with
...
NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=3
2, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(Nam
edType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClas
s=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('www.creativeedge.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('ot
herName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc
822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), ta
gSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))
), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('www.gokudos.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType
=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((
), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, t
agFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', Object
Identifier('<no value>')))).setComponents(None, None, IA5String('www.kredo.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', Obje
ctIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tag
Id=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('u
niformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setCompon
ents(None, None, IA5String('www.maestro.io', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))))""


$ ls Dennis\ Sheperd\ -\ Fight\ Your\ Fears\ \(2015\)\ \{WEB\}\ \[FLAC\]/
01. Where I Begin (Album Mix).flac  04. Dare to Dream (Album Mix).flac  07. Edge of the World (Radio Edit).flac  10. Two Worlds (Radio Edit).flac             13. Every Word (Club Radio Edit).flac  16. Wanting (Album Mix).flac
02. Heart of Courage.flac           05. Les Ailes (Album Mix).flac      08. We Are (Album Mix).flac              11. Runaway (Radio Mix).flac                 14. Summer (Album Mix).flac            17. So Many Hearts (Album Mix).flac
03. Starlight (Radio Edit).flac     06. Neocortex (Album Mix).flac      09. Come Alive (Album Mix).flac          12. Sky (Fight Your Fears) (Album Mix).flac  15. Bring You Home (Radio Edit).flac   cover.jpg


$ beet version
beets version 1.3.14
plugins: discogs, embedart, fetchart, ftintitle, info, scrub, zero



$ beet config

paths:
    default: $albumartist/$album/$track $title
    singleton: $albumartist/$album/$track $title
    comp: $albumartist/$album/$track $title

format_item: $album - $track - $albumartist - $artist - $title
fetchart:
    cautious: yes
    source: itunes amazon albumart
    minwidth: 700
    sources:
    - coverart
    - itunes
    - amazon
    - albumart
    - google
    - wikipedia
    maxwidth: 0
    google_search: no
    auto: yes
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    remote_priority: no
    enforce_ratio: no
ftintitle:
    auto: yes
    format: (feat. {0})
    drop: no
library: ~/Dropbox/beets_data/musiclibrary.blb
replace:
    '[\\/]': ''
    _: ''
    '[\x00-\x1f]': ''
    '[<>"\*\|]': ''
zero:
    fields: month day genre comments
    update_database: yes

ui:
    color: yes

plugins: fetchart discogs embedart scrub zero info ftintitle
directory: ~/music

import:
    move: no
    copy: yes
    write: yes
sort_item: album+ disc+ track+
scrub:
    auto: yes
discogs:
    tokenfile: discogs_token.json
    apikey: REDACTED
    apisecret: REDACTED
    source_weight: 0.5
embedart:
    compare_threshold: 0
    auto: yes
    ifempty: no
    maxwidth: 0

```

Didn't make any recent config changes and previous albums were importing successfully, but now it happens on all albums I attempt to import.

Any other data you could use?

**Comment by sampsyo** [comment] 2016-01-05 00:25
Wow; this is crazy. It looks at first glance like a bug in PyOpenSSL---maybe we can try asking that project for help?

It's coming from the discogs plugin, so one temporary solution would be to just disable that for now.

**Comment by bengadbois** [comment] 2016-01-05 00:39
You're right that disabling the discogs plugin fixed it.

**Comment by sampsyo** [comment] 2016-01-05 00:40
OK, great. Alas, I have no idea how to reproduce this, and Google is being surprisingly unhelpful. We may just need to wait for this to crop up for someone else too.

**Comment by sampsyo** [comment] 2016-02-01 01:53
Sadly, I think we need to close this issue for now because we don't have a way to reproduce it.

**Closed by sampsyo** 2016-02-01 01:53 UTC
Labels: needinfo
