### ISSUE TITLE
Please help, newbie, had it running, but halfway through it keeps stopping

### ISSUE THREAD

**Issue by EchoShauf** [beetbox/beets#5430] opened 2024-09-20 12:31 UTC
I keep getting "Error: The specified path is invalid while creating \\00.mp3", but this happens in the middle of it already working, I got it to import files but somehow it keeps stopping, and I cant find anything that is labeled or close to 00.mp3 or anything that has a file name of that. I have a lot of music that are unsorted, and I just want to have them be imported and sorted by artist, album, title

Edit: another error keeps coming up, "Error: The filename, directory name, or volume label syntax is incorrect while creating C:\Users\Jericho\AppData\Roaming\beets\‪D:" Windows? just trying to import "‪C:\Users\Jericho\Downloads\Music" to "D:\Beets Music"

### Problem

Running this config file:

```
beet import ‪C:\Users\Jericho\Downloads\Music
```

Led to this problem:

```
"Error: The specified path is invalid while creating \\00.mp3"
"Error: The filename, directory name, or volume label syntax is incorrect while creating C:\Users\Jericho\AppData\Roaming\beets\‪D:"
```

### Setup

* OS: Windows
* Python version: 3.12.6
* beets version: 2.0.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
plugins: fetchart embedart scrub chroma web
directory: D:\Beets Music
library: D:\Beets Music\Index Library
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no


paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes
    cover_names: cover front art album folder

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337

```

**Comment by JOJ0** [comment] 2024-09-21 06:21
Exact debug log when that happens would be interesting. It looks to me that maybe some metadata can't be found / is missing / a track gets named `\00` and that is illegal characters on windows. You have to find out which track exactly causes this and maybe a quickfix is to manually "pre-tag" it, delete it, move it away from beets and handle later. something like this....HTH

**Comment by EchoShauf** [comment] 2024-09-21 06:31
Is there a way I can view what track is it? I have 21K songs and if I try different albums instead of the whole library, it still does it. for example, if its music\assorted\album 1, it does the same, if its music\assorted\album 2 it would still give me the same error. 


does beets keep a log of what happened?

**Comment by EchoShauf** [comment] 2024-09-21 07:14
somehow its doing double for the database directory when creating the library. 

<img width="860" alt="{83E886E9-3055-4057-B71D-7E1C8B620539}" src="https://github.com/user-attachments/assets/ae5659e9-6054-46a4-87cb-bc12db65fa37">

**Comment by JOJ0** [comment] 2024-09-21 11:13
duplicate of https://github.com/beetbox/beets/discussions/5431#discussioncomment-10711305

**Closed** 2024-09-21 11:13 UTC
