### ISSUE TITLE
Unable to select choice on input

### ISSUE THREAD

**Issue by mtompkins** [beetbox/beets#2079] opened 2016-06-23 12:19 UTC
### Problem

After initial configuration, I am unable to make a choice when presented the candidates. I've tried this in terminal, terminal in screen, and various users with permissions.

I tried installing through apt as well as pip.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv (import /music/path.. )
```

Led to this problem:

```
Initial install and import.
```

### Setup

* OS: Ubuntu 16.04
* Python version: 2.7.11+
* beets version: 1.3.18
* Turning off plugins made problem go away (yes/no): n/a

My configuration (output of `beet config`) is:

```yaml
directory: /mnt/volume/media/music

import:
    copy: no
library: ~/.beetdata/musiclibrary.blb

plugins: chroma duplicates
duplicates:
    count: no
    full: no
    format: ''
    keys: []
    move: ''
    tag: ''
    path: no
    copy: ''
    tiebreak: {}
    album: no
    strict: no
    checksum: ''
    merge: no
    delete: no
chroma:
    auto: yes

```

**Comment by jackwilsdon** [comment] 2016-06-23 13:11
> Led to this problem:
```
Initial install and import.
```

What do you mean by this?

Are you not able to enter any text when the choice menu appears? (i.e. the one that lets you confirm the tagging, enter an MB UUID, keep tags etc).

**Comment by mtompkins** [comment] 2016-06-23 13:13
@jackwilsdon Correct and very peculiar. The terminal screen does accept a Ctrl-C but any of the standard menu choices (e.g. 1 for default, S for Skip) have no effect / do not work.

No keypress moves the menu selection forward (so not a numlock problem).

**Comment by mtompkins** [comment] 2016-06-23 13:15
Additional info if helpful:

- If I import with -A the process completes without issue.
- Fingerprinting also works with a `beet fingerprint` instruction

So it seems limited to this menu input.

**Comment by jackwilsdon** [comment] 2016-06-23 13:22
Very interesting. Do you think you could provide the full output from `beet import -vv [your-media]`?

**Comment by mtompkins** [comment] 2016-06-23 13:26
I'm sorry, not really an option to put it all out into the wild. What I will do is spin up a VM with the same Ubuntu version  and see if I can replicate on a sample set. If so, I'll be happy to provide that data. Will revert.

**Comment by jackwilsdon** [comment] 2016-06-23 13:29
> I'm sorry, not really an option to put it all out into the wild.

If you have sensitive song metadata, you could just replace them before pasting the output here?

**Comment by sampsyo** [comment] 2016-06-23 18:03
Hi! I think this is a duplicate of #2039 -- we should have a fix out, via an `audioread` update, very soon.

**Closed by sampsyo** 2016-06-23 18:03 UTC
Labels: needinfo
