### ISSUE TITLE
Single unmatched track when importing album consisting of 3 CDs

### ISSUE THREAD

**Issue by fortysix2ahead** [beetbox/beets#4142] opened 2021-11-12 20:21 UTC
Over the last weeks it happened from time to time that single tracks or albums are not matched by the importer. The album is complete, all is fine on MB side, the importer detects the correct album, but does match one single track of the album, although it's there. Today it happened again and out of the blue I noticed **when** it happens. It happened to me only, when the album consists of (at least??) 3 CDs. Is that really a coincidence?

Debug output is below, but it does not contain any pointers to a possible bug.

### Problem

Running this command in verbose (`-vv`) mode:

```sh
[beets>xxxxxxx]:/volume1/exchange/Music/Picard beet -vv import -L dark passion play
overlaying configuration: /var/services/homes/xxxxxxx/.config/beets/xxxxxxx/config-overlay.yaml
user configuration: /var/services/homes/xxxxxxx/.config/beets/config.yaml
data directory: /var/services/homes/xxxxxxx/.config/beets
plugin paths: /var/services/homes/xxxxxxx/Beets/plugins; /volume2/local/beets-plugins/beetsplug; /volume2/local/beets-kergoth/beetsplug
Sending event: pluginload
inline: adding item field multidisc
lyrics: Disabling google source: no API key configured.
library database: /var/services/homes/xxxxxxx/.config/beets/xxxxxxx/library.db
library directory: /volume2/music
Sending event: library_opened
Sending event: import_begin
yielding album 5386: Nightwish - Dark Passion Play
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_start
Looking up: /volume2/music/Nightwish/Dark Passion Play/1-01 The Poet and the Pendulum.mp3; /volume2/music/Nightwish/Dark Passion Play/1-02 Bye Bye Beautiful.mp3; /volume2/music/Nightwish/Dark Passion Play/1-03 Amaranth.mp3; /volume2/music/Nightwish/Dark Passion Play/1-04 Cadence of Her Last Breath.mp3; /volume2/music/Nightwish/Dark Passion Play/1-05 Master Passion Greed.mp3; /volume2/music/Nightwish/Dark Passion Play/1-06 Eva.mp3; /volume2/music/Nightwish/Dark Passion Play/1-07 Sahara.mp3; /volume2/music/Nightwish/Dark Passion Play/1-08 Whoever Brings the Night.mp3; /volume2/music/Nightwish/Dark Passion Play/1-09 For the Heart I Once Had.mp3; /volume2/music/Nightwish/Dark Passion Play/1-10 The Islander.mp3; /volume2/music/Nightwish/Dark Passion Play/1-11 Last of the Wilds.mp3; /volume2/music/Nightwish/Dark Passion Play/1-12 7 Days to the Wolves.mp3; /volume2/music/Nightwish/Dark Passion Play/1-13 Meadows of Heaven.mp3; /volume2/music/Nightwish/Dark Passion Play/2-01 The Poet and the Pendulum (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-02 Bye Bye Beautiful (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-03 Amaranth (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-04 Cadence of Her Last Breath (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-05 Master Passion Greed (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-06 Eva (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-07 Sahara (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-08 Whoever Brings the Night (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-09 For the Heart I Once Had (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-10 The Islander (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-11 Last of the Wilds (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-12 7 Days to the Wolves (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/2-13 Meadows of Heaven (instrumental).mp3; /volume2/music/Nightwish/Dark Passion Play/3-01 Escapist.mp3; /volume2/music/Nightwish/Dark Passion Play/3-02 Meadows of Heaven (orchestral version).mp3; /volume2/music/Nightwish/Dark Passion Play/3-03 The Poet and the Pendulum (demo version).mp3
Tagging Nightwish - Dark Passion Play
Searching for discovered album ID: 127836f5-11dc-45d9-82b4-7f98c9c35f1e
Requesting MusicBrainz release 127836f5-11dc-45d9-82b4-7f98c9c35f1e
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
primary MB release type: album
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Nightwish - Dark Passion Play (127836f5-11dc-45d9-82b4-7f98c9c35f1e)
Computing track assignment...
...done.
Success. Distance: 0.01
Album ID match recommendation is Recommendation.medium
Search terms: Nightwish - Dark Passion Play
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'dark passion play', 'artist': 'nightwish', 'tracks': '29'}
Requesting MusicBrainz release b74ebd63-a6c4-36e5-96bd-001c04f9beca
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
primary MB release type: album
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Nightwish - Dark Passion Play (b74ebd63-a6c4-36e5-96bd-001c04f9beca)
Computing track assignment...
...done.
Success. Distance: 0.33
Requesting MusicBrainz release fb9638ca-f6a5-3f0b-adae-28cf7ea9cd2c
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
primary MB release type: album
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Nightwish - Dark Passion Play (fb9638ca-f6a5-3f0b-adae-28cf7ea9cd2c)
Computing track assignment...
...done.
Success. Distance: 0.34
Requesting MusicBrainz release 20fe3729-c880-41fb-a8b1-68f6fd12c2c3
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
primary MB release type: album
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Nightwish - Dark Passion Play (20fe3729-c880-41fb-a8b1-68f6fd12c2c3)
Computing track assignment...
...done.
Success. Distance: 0.34
Requesting MusicBrainz release 16eb0ebe-dcc4-4730-adf3-c76c180ce1d8
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
primary MB release type: album
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Nightwish - Dark Passion Play (16eb0ebe-dcc4-4730-adf3-c76c180ce1d8)
Computing track assignment...
...done.
Success. Distance: 0.31
Requesting MusicBrainz release b8436777-c169-4c76-a822-82fb75ba26b7
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
primary MB release type: album
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Nightwish - Dark Passion Play (b8436777-c169-4c76-a822-82fb75ba26b7)
Computing track assignment...
...done.
Success. Distance: 0.31
Evaluating 6 candidates.

/volume2/music/Nightwish/Dark Passion Play/1-01 The Poet and the Pendulum.mp3
/volume2/music/Nightwish/Dark Passion Play/1-02 Bye Bye Beautiful.mp3
/volume2/music/Nightwish/Dark Passion Play/1-03 Amaranth.mp3
/volume2/music/Nightwish/Dark Passion Play/1-04 Cadence of Her Last Breath.mp3
/volume2/music/Nightwish/Dark Passion Play/1-05 Master Passion Greed.mp3
/volume2/music/Nightwish/Dark Passion Play/1-06 Eva.mp3
/volume2/music/Nightwish/Dark Passion Play/1-07 Sahara.mp3
/volume2/music/Nightwish/Dark Passion Play/1-08 Whoever Brings the Night.mp3
/volume2/music/Nightwish/Dark Passion Play/1-09 For the Heart I Once Had.mp3
/volume2/music/Nightwish/Dark Passion Play/1-10 The Islander.mp3
/volume2/music/Nightwish/Dark Passion Play/1-11 Last of the Wilds.mp3
/volume2/music/Nightwish/Dark Passion Play/1-12 7 Days to the Wolves.mp3
/volume2/music/Nightwish/Dark Passion Play/1-13 Meadows of Heaven.mp3
/volume2/music/Nightwish/Dark Passion Play/2-01 The Poet and the Pendulum (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-02 Bye Bye Beautiful (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-03 Amaranth (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-04 Cadence of Her Last Breath (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-05 Master Passion Greed (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-06 Eva (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-07 Sahara (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-08 Whoever Brings the Night (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-09 For the Heart I Once Had (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-10 The Islander (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-11 Last of the Wilds (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-12 7 Days to the Wolves (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/2-13 Meadows of Heaven (instrumental).mp3
/volume2/music/Nightwish/Dark Passion Play/3-01 Escapist.mp3
/volume2/music/Nightwish/Dark Passion Play/3-02 Meadows of Heaven (orchestral version).mp3
/volume2/music/Nightwish/Dark Passion Play/3-03 The Poet and the Pendulum (demo version).mp3 (29 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
Tagging:
    Nightwish - Dark Passion Play
URL:
    https://musicbrainz.org/release/127836f5-11dc-45d9-82b4-7f98c9c35f1e
(Similarity: 99.2%) (unmatched tracks) (3xCD, 2007, DE, Nuclear Blast, NB 1923-2, limited edition)
CD 1: Dark Passion Play
CD 2: Instrumentals
CD 3: Bonus Disc
Unmatched tracks (1):
 ! The Poet and the Pendulum (demo version) (#3-3) (13:41)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? b
Sending event: import
Sending event: cli_exit
```

The problem happened at least with these releases:
https://musicbrainz.org/release/127836f5-11dc-45d9-82b4-7f98c9c35f1e
https://musicbrainz.org/release/141fa8ae-f345-4d99-97c0-84ae27b6138f
https://musicbrainz.org/release/d43fa3e1-ec7c-416c-91f5-c6728307cf1a

### Setup

* OS: Synology
* Python version: 3.8 
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no):

**Comment by sampsyo** [comment] 2021-11-12 22:30
Can you please include your configuration (as indicated in the issue template)?

**Comment by wisp3rwind** [comment] 2021-11-14 10:47
The problem is most likely that the track in question is actually a video (on the disk, presumably the audio track was extracted when ripping?), see e.g. https://musicbrainz.org/release/127836f5-11dc-45d9-82b4-7f98c9c35f1e

**Comment by fortysix2ahead** [comment] 2021-11-15 11:00
Good catch! This seems to be issue! It's not a ripping thing, but the entry in MB is probably wrong. The 3CD release I have does not contain a video track. It's audio, but in MB it's marked as video. The same holds true for this:
https://musicbrainz.org/release/141fa8ae-f345-4d99-97c0-84ae27b6138f
Track #18 on CD 2 is the one that gives the problem an it is marked as video. Don't know if it's technically possible for a CD to have a video track in between audio tracks.

**Comment by wisp3rwind** [comment] 2021-11-15 12:33
> Good catch! This seems to be issue! It's not a ripping thing, but the entry in MB is probably wrong. The 3CD release I have does not contain a video track. It's audio, but in MB it's marked as video. The same holds true for this: https://musicbrainz.org/release/141fa8ae-f345-4d99-97c0-84ae27b6138f Track #18 on CD 2 is the one that gives the problem an it is marked as video. Don't know if it's technically possible for a CD to have a video track in between audio tracks.

I think multi-session (is that the correct term?) CDs are a thing, i.e. you can have both an audio session and a data session (with the video) on the same disc. I don't remember which one it was, but I've had (still have?) a CD like this.
So maybe the MB entry is not even wrong, but it does not correspond to the one you own?

**Comment by wisp3rwind** [comment] 2021-11-15 12:35
I'm going to close this, since it does not seem to be an issue with beets.

**Closed by wisp3rwind** 2021-11-15 12:35 UTC
Labels: needinfo
