### ISSUE TITLE
move with album and timid flags causes error in "select" mode

### ISSUE THREAD

**Issue by nershman** [beetbox/beets#4968] opened 2023-10-22 03:09 UTC
### Problem

It seems I can't run `beet move` with album mode and using the timid mode with select.

The expected behavior is to have an album's worth of filename changes shown to me at a time where I can choose yes/no/select instead of going through each file one by one. Another reasonable behavior would just be an error telling me both flags aren't supported, or not giving me the option to choose "select", only y/n

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv move -t -a
```

Led to this problem:

```
user configuration: /Users/sma/.config/beets/config.yaml
data directory: /Users/sma/.config/beets
plugin paths: 
Sending event: pluginload
library database: /Users/sma/Documents/Beets Test/musiclibrary.db
library directory: /Users/sma/Documents/Beets Test/test library
Sending event: library_opened
Moving 1 album (2 already in place).
Really move? (Yes/no/select) select

Traceback (most recent call last):
  File "/Users/sma/opt/miniconda3/lib/python3.9/site-packages/beets/dbcore/db.py", line 483, in __getattr__
    return self[key]
  File "/Users/sma/opt/miniconda3/lib/python3.9/site-packages/beets/dbcore/db.py", line 390, in __getitem__
    return self._get(key, raise_=True)
  File "/Users/sma/opt/miniconda3/lib/python3.9/site-packages/beets/dbcore/db.py", line 380, in _get
    raise KeyError(key)
KeyError: 'destination'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sma/opt/miniconda3/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/Users/sma/opt/miniconda3/lib/python3.9/site-packages/beets/ui/__init__.py", line 1285, in main
    _raw_main(args)
  File "/Users/sma/opt/miniconda3/lib/python3.9/site-packages/beets/ui/__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Users/sma/opt/miniconda3/lib/python3.9/site-packages/beets/ui/commands.py", line 1600, in move_func
    move_items(lib, dest, decargs(args), opts.copy, opts.album, opts.pretend,
  File "/Users/sma/opt/miniconda3/lib/python3.9/site-packages/beets/ui/commands.py", line 1573, in move_items
    objs = ui.input_select_objects(
  File "/Users/sma/opt/miniconda3/lib/python3.9/site-packages/beets/ui/__init__.py", line 398, in input_select_objects
    rep(obj)
  File "/Users/sma/opt/miniconda3/lib/python3.9/site-packages/beets/ui/commands.py", line 1576, in <lambda>
    [(o.path, o.destination(basedir=dest))]))
  File "/Users/sma/opt/miniconda3/lib/python3.9/site-packages/beets/dbcore/db.py", line 485, in __getattr__
    raise AttributeError(f'no such field {key!r}')
AttributeError: no such field 'destination'
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Mac OS 10.13.6
* Python version: 3.9.12
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): no. I don't have any installed yet.

My configuration (output of `beet config`) is:

```yaml
directory: '~/Documents/Beets Test/test library'
library: '~/Documents/Beets Test/musiclibrary.db'


import:
    copy: no
    write: no
    timid: yes 
    autotag: no 

per_disc_numbering: yes
paths:
    default: Album/%lower{%asciify{$albumartist}}/[$original_year] %lower{%asciify{$albumartist}} - %lower{%asciify{$album}} %lower{$atypes} [%lower{%asciify{$catalognum}}] %lower{%aunique{}}/%if{$multidisc, disc $disc_number/}$disc_and_track %lower{%asciify{$artist}} - %lower{%asciify{$title}}

```

**Comment by arsaboo** [comment] 2023-10-22 11:18
Looks like a duplicate of https://github.com/beetbox/beets/issues/2802

Doesn't look like this bug has been fixed.

**Comment by nershman** [comment] 2023-10-23 05:44
I see, thanks. I'll close this bug then. But first I want to ask about how to fix this. It looks like it might be simple, so I may have a go at it. in the pretend block there's an `if album` check with a list comprehension to avoid this error. We can do the same check for the `if confirm` block , no?

relevant code from `move_items` in commands.py:
```    
    if pretend:
        if album:
            show_path_changes(
                [
                    (item.path, item.destination(basedir=dest))
                    for obj in objs
                    for item in obj.items()
                ]
            )
        else:
            show_path_changes(
                [(obj.path, obj.destination(basedir=dest)) for obj in objs]
            )
    else:
        if confirm:
            objs = ui.input_select_objects(
                "Really %s" % act,
                objs,
                lambda o: show_path_changes(
                    [(o.path, o.destination(basedir=dest))]
```

**Comment by sampsyo** [comment] 2023-10-25 15:53
Yes, that sounds about right to me! At least to the degree that it looks worth trying out. Thanks for looking into it, @nershman!

**Closed by sampsyo** 2023-10-25 15:53 UTC
