### ISSUE TITLE
 chroma keyboard hangs

### ISSUE THREAD

**Issue by yakir12** [beetbox/beets#2039] opened 2016-06-07 18:32 UTC
### Problem
Keyboard hangs when the `chroma` plugin is included. `chroma` seems to work well (successfully figuring out tag-less files), but I can't type anything into the terminal (i.e. when presented with the Skip, Use as-is, Enter search, enter Id, aBort selections).
Here's what it looks like for a Bee Gees - Stayin’ Alive track:
```sh
$ beet -vv import -s a.mp3 
user configuration: /home/yakir/.config/beets/config.yaml
data directory: /home/yakir/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/yakir/musiclibrary.blb
library directory: /home/yakir/music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
chroma: chroma: fingerprinted '/home/yakir/a.mp3'
chroma: matched recordings [u'0fe88daf-24b8-4b81-8a85-608a888c909b', u'29ee8550-df33-4f83-adab-47e63b216102', u'41225d8c-ceac-490c-b122-e2334d741b61', u'81f5cf43-bbe0-4765-81f7-9d87807f99eb', u'92a2512f-639e-4f4a-987f-852a52f3f0c9', u'c174e3fb-7d5a-4cd0-b17f-b911a130d197', u'f2246047-e310-474a-9239-d05d5177abcc', u'fd52bd8b-b07f-45f1-a8f0-2dedaca14d35'] on releases [u'e3281abf-a0af-463f-9813-43bd5d7d673a', u'4e72827a-132a-4865-87ef-47c4bf05b39e', u'b538f594-3ef0-43b1-9f9c-7594b1ed3d6b', u'1818e232-6512-452c-ae34-9db9e697f3ff', u'3426a871-3d67-459d-bba2-fab0ff62504c', u'4cb34919-57a7-48a7-a43c-e8207b3aa34f', u'9166455c-b886-4d9e-9476-ceb87708aa32', u'd8040723-1384-4888-9ccd-24ab04d626fa', u'3cfb401d-a1e7-4d8a-a4e4-53889bf2c609', u'a5d0fe06-fa9c-4ded-ad08-6a4dd0722484', u'f859ed2b-22ec-3eb8-9e53-ef6837fd40bf', u'75ae0504-fb93-4046-86c1-82dc9a475c6f', u'a712ebdc-1f3f-4b6d-8ec0-b04027e90449', u'742c66b9-4562-48b0-9db0-16d3264982b4', u'0cbc87f6-0ea8-411e-9bc0-65f4cfbdf7a1', u'c031ef50-124b-3ab9-b3e5-f18ef1e9a8d0', u'f17bfa08-896f-47eb-9187-a216065e61fa', u'873188a1-a772-4232-8882-1e61585c0443', u'1a0ce879-db2c-4d0f-b769-dd88f757f1f6', u'da85bd3c-4012-3692-8b9b-ee2059e3bc98', u'81557219-8b12-48b9-8a85-0cd3ee121820', u'8e054e8a-9c73-45ca-9da9-12316b35889e', u'2da82468-7997-368e-8424-c2b5f91ecd1f', u'317df471-8569-4a09-968d-1c1f2810ff32', u'3177a9e3-6d6e-4f34-ba92-b07cfb6f74e3', u'12cc16cb-5649-4e1a-bd10-a8a496280990', u'f6032bc7-a8fa-481c-9b03-bfeb2d2ab5c7', u'8eaeea45-011a-432d-a2b4-08db7da479c7', u'b3a6d500-aca5-46d8-a1a4-308c58a08de2', u'09d82e9f-4b95-464e-aa45-2c0b24295bad', u'd075c24d-08dc-4197-8e81-12337d214f2d', u'084a82ee-cabf-4884-8ae5-dbe166a2391b', u'c54f026b-4e2b-44e4-a281-68a2f7cae1da', u'1a5fbd22-9a0a-4252-9bb0-60f3f1e14750', u'4e813375-e6d9-4ee9-bf4a-b4c875f24523', u'98018b1f-7e70-3b66-89ea-886ad7011b94', u'af9f5d9f-c7d6-338c-9b00-3a2235000844', u'cd4427bc-ef3d-3c34-bce5-fce1aa9a32e9', u'6136bbcd-fdcd-47b7-bad9-478571076706', u'a215b99f-7c1c-4349-8995-1e6c601988f0', u'd981b0a8-32a3-475f-bce9-c61b05fd7a04', u'1555f9b3-a019-4f52-acfc-f8dd3b682805', u'59c3a26b-1120-4e12-932c-643fa764e9fb', u'39635d46-05cf-4f57-ade9-275d1c3393fe', u'c8b5f635-3026-320b-a0cb-c8b93557b545', u'c9b44c01-250f-3fbd-9e33-233b79cd7ac9', u'60f06d3c-550b-45c9-84d0-3826fe64ab03', u'9a881120-6baf-4b1d-b8be-51e8d4c09660', u'8756db30-6c42-427e-909f-cbdcb75f3bd3', u'91bf2254-0f2c-4420-a7c3-a2e6dbf6484d', u'9ee370d1-0384-4ed6-8ffa-dd51b83c6fde', u'81457581-1e0a-49c1-bcb5-be0f0a233d9e', u'aea6e02c-06e2-3711-a7f8-9c7ee4ce13ed', u'9517e0a7-b86f-3e5e-85db-33f093c7ba21', u'3b40797b-1afb-482b-ae39-671379b1c3ca', u'3246ec4d-89c6-4066-b6b7-fa6735a700a8', u'4443733f-82b4-4d45-9007-b82f8c5a5fe0', u'c0b3f020-89ad-4d73-b8f3-a1147a4a32a4', u'd2da407c-314a-442a-9095-8b3b4674a302', u'b7711fb5-8526-4e88-9f64-e8784857516a', u'7d69383d-d092-3871-8cce-3f6f361c0e5d', u'26906f4a-7ef3-3b73-9c24-ff84fa492262', u'b74306eb-15ac-4d9c-9780-a86ad6a87a10', u'03bb2467-bac5-47b9-acea-ad5c327d04e3', u'd54219dc-d469-4d92-9173-4546060f5f73', u'e32b7653-0d93-4323-ab8b-6fb2b8b10b56', u'bc1d1b8e-c1d1-4804-a587-312d88c686e6', u'b599c035-2be6-431b-8207-877a0571fad6', u'5426fd78-0d36-4220-8b9f-acb5226100c3', u'935e0a99-94c6-4aa0-a9d5-24ae036a9534', u'de842fe1-8c90-48de-9bd2-b5709d5f8f0c', u'dee66960-d370-41c8-9471-2ea662a81841', u'44271fb8-9230-4a4d-8157-346c4cb3876a', u'c5797a9a-fb0b-470c-8414-a721d0ff7789', u'ab5eecdb-56ff-4425-b179-d07d956eb5d6', u'25667019-50d5-45a3-b3cf-3922081417aa', u'e673e769-4bce-4796-a236-c411e9d3d19a', u'4d6c420b-12a6-4c1b-bc22-f7e8d96a2d26', u'25d4f705-f826-4299-9bea-732a526884c1', u'af956674-3f81-3c15-990c-c59d0b9d9c1c']
Looking up: /home/yakir/a.mp3
Item search terms:  - 
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
chroma: acoustid item candidates: 5
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Sending event: trackinfo_received
Found 5 candidates.

/home/yakir/a.mp3
Sending event: before_choose_candidate
Finding tags for track " - ".
Candidates:
1. Bee Gees - Stayin’ Alive (70.0%) (title)
2. Bee Gees - Stayin Alive (70.0%) (title)
3. Bee Gees - Stayin' Alive (70.0%) (title)
4. Bee Gees - Stayin' Alive (70.0%) (title)
5. Bee Gees - Stayin' Alive (50.0%) (title, length)
# selection (default 1), Skip, Use as-is, Enter search, enter Id, aBort?
```

Note that the keyboard hangs irrelevant of which track it is, *unless* the match is high enough for `beets` to import without any prompt. 

Here's a link to the music files that trigger the bug (not that it matters): [link](https://www.dropbox.com/s/b2p7tcb14d8d96o/a.mp3?dl=0)

### Setup

* OS: Debian GNU/Linux stretch/sid
* Python version: 2.7.11+
* beets version: 1.3.18
* Turning off plugins made problem go away: yes 

My configuration (output of `beet config`) is:

```yaml
directory: /home/yakir/music
library: ~/musiclibrary.blb

plugins: chroma
chroma:
    auto: yes
```

**Comment by p5a0u9l** [comment] 2016-06-08 05:00
can confirm - same on osx el capitan. I have a similar config file as op.

**Comment by sampsyo** [comment] 2016-06-08 05:54
Wow; weird! Can you both give a little more detail about how you installed the Chromaprint stuff? Did you install the executable or the library? Which version? Are you using ffmpeg, gstreamer, or something else (on OS X, it may be neither because codecs are built-in)?

**Comment by yakir12** [comment] 2016-06-08 06:03
I used the Static binaries for the `fpcalc` tool from the Chromaprint website, version 1.3.1. I had `ffmpeg` already installed:
```bash
$ ffmpeg -version
ffmpeg version 3.0.2-3 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 5.3.1 (Debian 5.3.1-21) 20160528
configuration: --prefix=/usr --extra-version=3 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264
libavutil      55. 17.103 / 55. 17.103
libavcodec     57. 24.102 / 57. 24.102
libavformat    57. 25.100 / 57. 25.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 31.100 /  6. 31.100
libavresample   3.  0.  0 /  3.  0.  0
libswscale      4.  0.100 /  4.  0.100
libswresample   2.  0.101 /  2.  0.101
libpostproc    54.  0.100 / 54.  0.100
```

**Comment by sampsyo** [comment] 2016-06-08 06:20
Thanks!

Perhaps unsurprisingly, I can't seem to reproduce this:

```sh
$ fpcalc -v
fpcalc version 1.3.1
$ beet -v imp -ts [...]
[...]
chroma: acoustid item candidates: 1
[...]
Apply, More candidates, [S]kip, Use as-is, Enter search, enter Id, aBort,
eDit, edit Candidates? s
Sending event: import_task_choice
Sending event: import
Sending event: cli_exit
```

I'm not sure what what's different between our systems. Any ideas about what else to try?

**Comment by yakir12** [comment] 2016-06-08 06:26
Would it help to ssh into my computer?

**Comment by yakir12** [comment] 2016-06-08 07:23
I tried running all the `beet import` from a different terminal emulator (`terminator` instead of `xterm`) and the behavior did not change, still hangs.

**Comment by sampsyo** [comment] 2016-06-08 16:22
Yeah, debugging *in vivo* over SSH could indeed work. Please feel free to email me directly (email's on my profile).

**Comment by capsgetpeeled** [comment] 2016-06-09 17:27
Same issue here on OS X 10.11 El Capitan. Installed via pip, other stuff via brew. Using the -Vv flag shows that beets is still chugging away scanning files but cannot enter any keyboard input (including crontrol-c) into that terminal window. Tried from different users on the same machine as well as alternate Terminal emulators. beets (at) capsgetpeeled (dot) com if anyone wants to teamviewer in or something and check it out.
Thanks!

**Comment by sampsyo** [comment] 2016-06-12 19:23
Could those of you who are running into this confirm the version of ffmpeg you have installed?

**Comment by capsgetpeeled** [comment] 2016-06-12 19:37
Mini:~ blackfly$ ffmpeg -version
ffmpeg version 3.0.2 Copyright (c) 2000-2016 the FFmpeg developers
built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.0.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-vda
libavutil      55. 17.103 / 55. 17.103
libavcodec     57. 24.102 / 57. 24.102
libavformat    57. 25.100 / 57. 25.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 31.100 /  6. 31.100
libavresample   3.  0.  0 /  3.  0.  0
libswscale      4.  0.100 /  4.  0.100
libswresample   2.  0.101 /  2.  0.101
libpostproc    54.  0.100 / 54.  0.100

And i just noticed this machine is running 10.9, not 10.11 as previously stated.

**Comment by sampsyo** [comment] 2016-06-12 19:55
Thank you, @capsgetpeeled! That helped.

I've narrowed down the problem to an audioread bug: https://github.com/beetbox/audioread/issues/32

So I'm going to close this beets issue. Please follow along there! I hope to fix this soon.

**Closed** 2016-06-12 20:00 UTC
Labels: needinfo
