### ISSUE TITLE
beets cannot write the albumtype tags to the file metadata

### ISSUE THREAD

**Issue by djfjeff** [beetbox/beets#5045] opened 2023-12-13 12:31 UTC
I reimported my library from scratch after an issue I had. Everything imported correctly and the data in the beet database are OK. However, everytime I run `beet write`, it always try to write the albumtype metadata to the file. Even if I let it write, it will not change the metadata of the file and insist to do it again at the next `beet write` command.

I don't understand since I used scrub, zero and from_scratch when I imported my library, I was expecting the file tag to already reflect the right information.

### Problem

```sh
$ beet info 01\ -\ The\ Ecstasy\ of\ Gold\ _\ Enter\ Sandman.flac
...
           albumtype: album
          albumtypes: album; live
...
```

```sh
$ exiftool 01\ -\ The\ Ecstasy\ of\ Gold\ _\ Enter\ Sandman.flac
...
Releasetype                     : live
Musicbrainz Albumtype           : live
...
```

```sh
$ beet -vv --plugins= write -p ecstasy

user configuration: /home/xyz/.config/beets/config.yaml
data directory: /home/xyz/.config/beets
plugin paths: 
Sending event: pluginload
library database: /mnt/xyz/musiclibrary.db
library directory: /mnt/xyz/music
Sending event: library_opened
Parsed query: AndQuery([AnyFieldQuery('ecstasy', ('artist', 'title', 'comments', 'album', 'albumartist', 'genre'), SubstringQuery)])
Parsed sort: NullSort()
Metallica - Live Shit: Binge & Purge - The Ecstasy of Gold / Enter Sandman
  albumtype: album -> live
```

### Setup

* OS: Freebsd 13.2
* Python version: python 3.9
* beets version: 1.6.1 installed from git today (2023-12-13)
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
...
zero:
  auto: yes
  fields: comments

scrub:
  auto: yes

import:
  move: yes
  write: yes
  from_scratch: yes
  timid: no
...
```

**Comment by djfjeff** [comment] 2023-12-13 12:43
And just to add, it seems the beets is still writing something to the file according to the timestamp of the file.

Before running `beet write` :
```
ls -l 01\ -\ The\ Ecstasy\ of\ Gold\ _\ Enter\ Sandman.flac 

169919939 Dec 12 21:17 01 - The Ecstasy of Gold _ Enter Sandman.flac
```

After running `beet write` :
```
ls -l 01\ -\ The\ Ecstasy\ of\ Gold\ _\ Enter\ Sandman.flac 
169919939 Dec 13 07:42 01 - The Ecstasy of Gold _ Enter Sandman.flac
```

However, `beet write` still insist to try to write the albumtype data next time I run it and the file does not reflect the right data again.

**Comment by JOJ0** [comment] 2023-12-19 09:48
Duplicate of #4648

**Comment by JOJ0** [comment] 2023-12-19 10:16
But thanks anyway for the report, can you confirm that the details I have just added to #4648 (command ouputs) exactly reflect what you are facing here @djfjeff ? Thanks a lot!

**Comment by djfjeff** [comment] 2023-12-19 12:37
@JOJ0 I am not sure it is the same case. I had issue in the past with the albumtypes (with an `s` at the end) and the `[;';a;l;b;u;m;';]` issue before with beets 1.6.0. (Tracked in #4582 )

However, I completely deleted my database, upgraded to 1.6.1 and reimported from scratch. I don't have issue with albumtypes and `[;';a;l;b;u;m;';]` anymore.

My issue seems to be that beets is unable to write the albumtype tag even it if is a single string (album). I also have the problem with other tags that appears at every `beet write` invocation, for example :

```
beet write Intro School

Nirvana - In The Bloom 1990 Tour - Intro/School
  mb_artistid:  -> 125246
  mb_albumartistid:  -> 125246
  albumtype:  -> Unofficial Release 
```

beets try to write the mb_artistid and mb_albumartistid everytime, same as with the albumtype tag.

**Comment by JOJ0** [comment] 2023-12-19 12:44
Hi, @djfjeff I'm very sorry, my mistake, we have so many of these reports already, I got confused, haha ;-) This is the one I'm talking about: #4715

Can you confirm that this is your issue?

I'lll update my posts above now to reflect the correct issue ID. Sorry again for the confusion!

**Comment by djfjeff** [comment] 2023-12-19 12:59
@JOJ0 yes, it seems to be the same issue as yours.

However, I don't think that your fix idea (ignore the albumtype tag) would be working in my case because as you can see, I have the same issue with other fields (mb_artistid, mb_albumartistid, etc) that show the same behavior : beets try to write it everytime, the file timestamp get updated but nothing change in the file metadata on disk.

**Closed** 2023-12-21 16:46 UTC

**Comment by djfjeff** [comment] 2023-12-21 18:10
@JOJ0 I am curious about the close, what complete this request? I do not see any linked PR or merge attached to this issue that would fix this?

**Comment by JOJ0** [comment] 2023-12-21 18:40
> @JOJ0 I am curious about the close, what complete this request? I do not see any linked PR or merge attached to this issue that would fix this?

https://github.com/beetbox/beets/issues/5045#issuecomment-1862438768

**Comment by djfjeff** [comment] 2023-12-21 18:47
@JOJ0 Like I said, I don't agree with your solution to ignore the field as a fix. And like I showed, the issue is present with other type of field anyway in my case, just that the albumtype is the more frequent one. I will reopen as I think something in beets is not able to properly write tag to the file.

**Comment by JOJ0** [comment] 2023-12-21 18:58
The point is: We have a duplicate. I hear you and probably same issue with your other fields. It needs to be tackled but having several issues open does not help. Please lets continue on brainstorming about a solution over there. My solution there is just an idea and might be wrong.

**Comment by djfjeff** [comment] 2023-12-21 19:27
I agree about this, my point is that your solution only cover the albumtype field and it is to ignore the field, which is not a solution for other affected fields in my opinion... If we can cover the other fields in the same issue, I am OK with that.

**Comment by JOJ0** [comment] 2023-12-21 19:35
> 

Yes, I was about to add that over there. Give me a minute ;-) We could keep this open since your report is good and detailed but I want to prevent to split (again) all the information in dozens of issues. Thus: I'd like to keep it closed so people find that one issue over there _only_ Please double check what I wrote over there in the description and in the my latest post! Thanks for your help and many thanks for a good report! :-)
