### ISSUE TITLE
Output formatted with timecodes

### ISSUE THREAD

**Issue by EanNewton** [beetbox/beets#4409] opened 2022-07-09 23:33 UTC
### Problem

All output is unusable as text is interlaced with what appears to be timestamps. This happens with a majority of my music collection, not just the sample output below.

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import D:\Music --group-albums
```

Led to this problem:

With verbose:
```
D:\Music\Akon Discography @ 320 (6 Albums)(RAP)(by dragan09)\Mixtapes\2009 - Akon - Marijuana Mixtape\02-Jim Jones Ft. Akon-Click Clack.mp3 (1 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
Finding tags for album "Jim Jones Ft. Akon - Akon-Marijuana.Mixtape".
Candidates:
1. Akon - The Koncrete Mixtape (←[31;01m19.8%←[39;49;00m) ←[33;01m(missing tracks, artist, album, ...)←[39;49;00m ←[37m(CD, 2012, US)←[39;49;00m
2. Akon - Freedom Mixtape (←[31;01m19.1%←[39;49;00m) ←[33;01m(missing tracks, artist, album, ...)←[39;49;00m ←[37m(Digital Media, 2008, US)←[39;49;00m
3. Akon - Konvict Mixtape, Vol. 1 (←[31;01m19.1%←[39;49;00m) ←[33;01m(missing tracks, artist, album, ...)←[39;49;00m ←[37m(Digital Media, 2013, XW, BU Vision)←[39;49;00m
4. Various Artists - Marijuana Mixtape (←[31;01m16.8%←[39;49;00m) ←[33;01m(missing tracks, tracks, album)←[39;49;00m
5. Radha - Akon (←[31;01m10.2%←[39;49;00m) ←[33;01m(missing tracks, artist, album, ...)←[39;49;00m
# selection (default ←[36;01m1←[39;49;00m), ←[34;01mS←[39;49;00mkip, ←[34;01mU←[39;49;00mse as-is, as ←[34;01mT←[39;49;00mracks, ←[34;01mG←[39;49;00mroup albums,
←[34;01mE←[39;49;00mnter search, enter ←[34;01mI←[39;49;00md, a←[34;01mB←[39;49;00mort? Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
```

Without verbose:
```
Correcting tags from:
    ←[31;01mAphex←[39;49;00m ←[31;01mTw←[39;49;00min - Joyrex J4 EP
To:
    ←[31;01mCaustic←[39;49;00m ←[31;01mW←[39;49;00min←[31;01mdow←[39;49;00m - Joyrex J4 EP
URL:
    https://musicbrainz.org/release/6c279fc8-9614-4584-a86c-f059db727487
(Similarity: ←[33;01m89.1%←[39;49;00m) ←[33;01m(artist)←[39;49;00m ←[37m(12" Vinyl, 1992, GB, Rephlex, CAT 004 EP)←[39;49;00m
 * Pop←[31;01m C←[39;49;00morn -> Pop←[31;01mc←[39;49;00morn
←[36;01m[A]←[39;49;00mpply, ←[34;01mM←[39;49;00more candidates, ←[34;01mS←[39;49;00mkip, ←[34;01mU←[39;49;00mse as-is, as ←[34;01mT←[39;49;00mracks, ←[34;01mG←[39;49;00mroup albums,
←[34;01mE←[39;49;00mnter search, enter ←[34;01mI←[39;49;00md, a←[34;01mB←[39;49;00mort?
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Windoes 10 x64 Pro 21H1 19043.1766
* Python version: 3.6.8
* beets version: 1.6.0
* Turning off plugins made problem go away (yes/no): No plugins installed

My configuration (output of `beet config`) is:

```yaml
directory: D:\beet\Music
library: ~\AppData\Roaming\beets\musiclibrary.db
import:
    move: yes
```

**Comment by EanNewton** [comment] 2022-07-09 23:35
During the above run the following error was also encountered:

```

Correcting tags from:
    ←[31;01mJim Jones Ft. ←[39;49;00mAkon - ←[31;01mAk←[39;49;00mon←[31;01m-Ma←[39;49;00mr←[31;01mijuana.←[39;49;00mMixtape
To:
    Akon - ←[31;01mThe K←[39;49;00mon←[31;01mc←[39;49;00mr←[31;01mete ←[39;49;00mMixtape
URL:
    https://musicbrainz.org/release/331be281-fa9f-4414-a9af-cff215bb4f23
(Similarity: ←[31;01m19.8%←[39;49;00m) ←[33;01m(missing tracks, artist, album, tracks, year)←[39;49;00m ←[37m(CD, 2012, US)←[39;49;00m
 * ←[31;01mClick←[39;49;00m ←[31;01mClack (Ft. Akon)←[39;49;00m -> ←[31;01mKeep←[39;49;00m ←[31;01mUp←[39;49;00m ←[33;01m(title)←[39;49;00m
Missing tracks (14/15 - 93.3%):
←[33;01m ! Hurt Somebody                (# 1) (4:09)←[39;49;00m
←[33;01m ! Honey I’m Home (Noodles mix) (# 3) (2:26)←[39;49;00m
←[33;01m ! Top Chef                     (# 4) (4:40)←[39;49;00m
←[33;01m ! Still a Survivor             (# 5) (4:19)←[39;49;00m
←[33;01m ! So High                      (# 6) (4:34)←[39;49;00m
←[33;01m ! Self Made                    (# 7) (4:33)←[39;49;00m
←[33;01m ! Make It in the City          (# 8) (3:25)←[39;49;00m
←[33;01m ! Do It                        (# 9) (4:03)←[39;49;00m
←[33;01m ! Long Gone                    (#10) (4:11)←[39;49;00m
←[33;01m ! Weekend                      (#11) (3:33)←[39;49;00m
←[33;01m ! Survivor                     (#12) (3:40)←[39;49;00m
←[33;01m ! Searching for Love           (#13) (4:20)←[39;49;00m
←[33;01m ! Time or Money                (#14) (4:43)←[39;49;00m
←[33;01m ! Conspiracy                   (#15) (3:57)←[39;49;00m
←[34;01mA←[39;49;00mpply, ←[34;01mM←[39;49;00more candidates, ←[34;01mS←[39;49;00mkip, ←[34;01mU←[39;49;00mse as-is, as ←[34;01mT←[39;49;00mracks, ←[34;01mG←[39;49;00mroup albums,
←[34;01mE←[39;49;00mnter search, enter ←[34;01mI←[39;49;00md, a←[34;01mB←[39;49;00mort?
Enter one of A, M, S, U, T, G, E, I, B: a
Sending event: import_task_choice
found duplicates: [206]
default action for duplicates: a
This album is already in the library!
Old: 1 items, MP3, 320kbps, 4:32, 10.4 MiB
New: 1 items, MP3, 320kbps, 3:45, 8.6 MiB
←[36;01m[S]←[39;49;00mkip new, ←[34;01mK←[39;49;00meep all, ←[34;01mR←[39;49;00memove old, ←[34;01mM←[39;49;00merge all?
Traceback (most recent call last):
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\util\__init__.py", line 496, in move
    os.replace(path, dest)
OSError: [WinError 17] The system cannot move the file to a different disk drive: '\\\\?\\C:\\Users\\eanne\\AppData\\Local\\Temp\\tmpp2oqg4qo.jpg' -> '\\\\?\\D:\\beet\\Music\\Celia Yancey\\Yancey\\cover.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.6.0', 'console_scripts', 'beet')()
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\ui\__init__.py", line 1285, in main
    _raw_main(args)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\ui\__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\ui\commands.py", line 973, in import_func
    import_files(lib, paths, query)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\ui\commands.py", line 943, in import_files
    session.run()
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\util\pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\util\pipeline.py", line 358, in run
    self.coro.send(msg)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\util\pipeline.py", line 170, in coro
    task = func(*(args + (task,)))
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\importer.py", line 1569, in manipulate_files
    session=session,
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\importer.py", line 766, in manipulate_files
    plugins.send('import_task_files', session=session, task=self)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\plugins.py", line 488, in send
    result = handler(**arguments)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\plugins.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beetsplug\fetchart.py", line 1063, in assign_art
    self._set_art(task.album, candidate, not self.src_removed)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beetsplug\fetchart.py", line 1048, in _set_art
    album.set_art(candidate.path, delete)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\library.py", line 1317, in set_art
    util.move(path, artdest)
  File "C:\Users\eanne\AppData\Local\Programs\Python\Python36\lib\site-packages\beets\util\__init__.py", line 499, in move
    prefix=py3_path(b'.' + os.path.basename(dest)),
TypeError: can't concat str to bytes
PS C:\Windows\system32>
```

**Comment by jackwilsdon** [comment] 2022-07-09 23:35
Duplicate of #2607 (those aren't timestamps, they're color escape sequences).

**Comment by jackwilsdon** [comment] 2022-07-09 23:37
Just seen your latest comment - it should be fixed in the latest source version of beets (see #4252).

**Closed** 2022-07-09 23:38 UTC
Labels: duplicate

**Comment by EanNewton** [comment] 2022-07-10 00:15
Confirmed source version 1.6.0 fixes the escape sequences.
