### ISSUE TITLE
Basic Problems with GMusic Plugin

### ISSUE THREAD

**Issue by gboysko** [beetbox/beets#2674] opened 2017-08-27 19:12 UTC
### Problem

I was simply trying to upload music using the gmusic plugin. Similar to #2660, I'm seeing basic errors when using this plugin:

```sh
$ beet gmusic-upload shellac
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beetsplug/gmusic.py", line 61, in upload
    ui.print_('Uploading your files...')
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 134, in print_
    assert isinstance(strings[0], six.text_type)
AssertionError
```

Not sure if I am using an outdated version of Python (2.7)

### Setup

* OS: Ubuntu 16.04
* Python version: 2.7.12
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): No--it is a problem with a plugin.

My configuration (output of `beet config`) is:

**Comment by sampsyo** [comment] 2017-08-27 21:37
Hello! Yes, this is indeed a duplicate of #2660. We've committed a fix, and a release with the change will be out soon. Or, you can try running the latest source from git—there are instructions on the FAQ.

**Closed by sampsyo** 2017-08-27 21:37 UTC
