### ISSUE TITLE
test_constrained_exception hangs the test suite in py3

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2078] opened 2016-06-23 09:05 UTC
See https://github.com/beetbox/beets/blob/master/test/test_pipeline.py#L160

I have to `Ctrl+C` to stop it. 

When I `Ctrl+C` I get this:

``` sh
$ python3-tox -e py35-test -- test/test_pipeline.py -v
GLOB sdist-make: /home/johnny/src/beets/setup.py
py35-test inst-nodeps: /home/johnny/src/beets/.tox/dist/beets-1.3.19.zip
py35-test installed: beautifulsoup4==4.4.1,beets==1.3.19,click==6.6,cookies==2.2.1,coverage==4.1,enum34==1.1.6,Flask==0.11.1,itsdangerous==0.24,jellyfish==0.5.5,Jinja2==2.8,MarkupSafe==0.23,mock==2.0.0,munkres==1.0.7,musicbrainzngs==0.6,mutagen==1.32,nose==1.3.7,nose-show-skipped==0.1,pathlib==1.0.1,pbr==1.10.0,pylast==1.6.0,python-mpd2==0.5.5,pyxdg==0.25,PyYAML==3.11,rarfile==2.8,requests==2.10.0,responses==0.5.1,six==1.10.0,Unidecode==0.4.19,Werkzeug==0.11.10
py35-test runtests: PYTHONHASHSEED='418410290'
py35-test runtests: commands[0] | nosetests test/test_pipeline.py -v
test_pull (test.test_pipeline.BubbleTest) ... ok
test_run_parallel (test.test_pipeline.BubbleTest) ... ok
test_run_sequential (test.test_pipeline.BubbleTest) ... ok
test_constrained (test.test_pipeline.ConstrainedThreadedPipelineTest) ... ok

test_constrained_exception (test.test_pipeline.ConstrainedThreadedPipelineTest) ... ^CERROR: KEYBOARDINTERRUPT

----------------------------------------------------------------------
Ran 5 tests in 4.996s

OK
^CException ignored in: <module 'threading' from '/usr/lib64/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 1288, in _shutdown
ERROR: keyboardinterrupt
    t.join()
  File "/usr/lib64/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

```

This occurs in both py 3.4 and 3.5. All other pipeline tests pass

**Comment by sampsyo** [comment] 2016-06-23 17:57
Wow; I have no idea what could be causing this. This will take some true debugging heroics to understand.

**Comment by jrobeson** [comment] 2016-06-27 02:10
interesting. I run it outside of tox and all the tests pass.

**Comment by jrobeson** [comment] 2016-06-27 02:26
oops, i was running with the py2 version of nose.. so scratch that :(

**Comment by jrobeson** [comment] 2016-06-27 02:32
Here's how I got a proper traceback though: https://dzone.com/articles/inspecting-thread-dumps-hung


```sh
PYTHONFAULTHANDLER=true nosetests-3.5  test/test_pipeline.py
....Fatal Python error: Aborted

Thread 0x00007ff66e16e700 (most recent call first):
  File "/usr/lib64/python3.5/threading.py", line 293 in wait
  File "/usr/lib64/python3.5/queue.py", line 133 in put
  File "/home/johnny/src/beets/beets/util/pipeline.py", line 261 in run
  File "/usr/lib64/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib64/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007ff67de4b700 (most recent call first):
  File "/usr/lib64/python3.5/threading.py", line 1070 in _wait_for_tstate_lock
  File "/usr/lib64/python3.5/threading.py", line 1054 in join
  File "/home/johnny/src/beets/beets/util/pipeline.py", line 429 in run_parallel
  File "/usr/lib64/python3.5/unittest/case.py", line 214 in handle
  File "/usr/lib64/python3.5/unittest/case.py", line 765 in assertRaises
  File "/home/johnny/src/beets/test/test_pipeline.py", line 170 in test_constrained_exception
  File "/usr/lib64/python3.5/unittest/case.py", line 638 in run
  File "/usr/lib64/python3.5/unittest/case.py", line 686 in __call__
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 152 in runTest
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 134 in run
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 46 in __call__
  File "/usr/lib/python3.5/site-packages/nose/suite.py", line 225 in run
  File "/usr/lib/python3.5/site-packages/nose/suite.py", line 178 in __call__
  File "/usr/lib/python3.5/site-packages/nose/suite.py", line 225 in run
  File "/usr/lib/python3.5/site-packages/nose/suite.py", line 178 in __call__
  File "/usr/lib/python3.5/site-packages/nose/suite.py", line 225 in run
  File "/usr/lib/python3.5/site-packages/nose/suite.py", line 178 in __call__
  File "/usr/lib/python3.5/site-packages/nose/core.py", line 62 in run
  File "/usr/lib/python3.5/site-packages/nose/core.py", line 207 in runTests
  File "/usr/lib64/python3.5/unittest/main.py", line 94 in __init__
  File "/usr/lib/python3.5/site-packages/nose/core.py", line 121 in __init__
  File "/usr/bin/nosetests-3.5", line 9 in <module>
bash: “PYTHONFAULTHANDLER=true nos…” terminated by signal SIGABRT (Abort)
```

**Comment by jrobeson** [comment] 2016-06-27 02:43
if you kids wanna play along at home (in fact, please do). then you can run this test with python3 even on the master branch. Just remove the skip line here: https://github.com/beetbox/beets/blob/master/test/test_pipeline.py#L165

**Comment by wordofglass** [comment] 2016-06-28 09:12
I think I've tracked this down to a race condition on queue invalidation.

Note the change from [2.7](https://github.com/python/cpython/blob/2.7/Lib/Queue.py#L125) to [3.5](https://github.com/python/cpython/blob/master/Lib/queue.py#L132) (`==` to `>=`). I haven't looked up when exactly this was committed.

Now in
```python
    def put(self, item, block=True, timeout=None):
        '''Put an item into the queue.
        If optional args 'block' is true and 'timeout' is None (the default),
        block if necessary until a free slot is available. If 'timeout' is
        a non-negative number, it blocks at most 'timeout' seconds and raises
        the Full exception if no free slot was available within that time.
        Otherwise ('block' is false), put an item on the queue if a free slot
        is immediately available, else raise the Full exception ('timeout'
        is ignored in that case).
        '''
        with self.not_full:
            if self.maxsize > 0:
                if not block:
                    if self._qsize() >= self.maxsize:
                        raise Full
                elif timeout is None:
                    while self._qsize() >= self.maxsize:
                        self.not_full.wait()
                elif timeout < 0:
                    raise ValueError("'timeout' must be a non-negative number")
                else:
                    endtime = time() + timeout
                    while self._qsize() >= self.maxsize:
                        remaining = endtime - time()
                        if remaining <= 0.0:
                            raise Full
                        self.not_full.wait(remaining)
            self._put(item)
            self.unfinished_tasks += 1
            self.not_empty.notify()
```
some thread could be waiting in the `self.not_full.wait()` loop because the pipeline is full (not too unlikely when the pipeline's `maxsize` is 16 and 1000 tasks are passed through it).

If now a switch to the `_work` thread occurs which in turn raises the exception, `PipelineThread.abort_all()` will invalidate the queues like this:
```python
        q.maxsize = 0
        q._qsize = _qsize
        q._put = _put
        q._get = _get
        q.not_empty.notifyAll()
        q.not_full.notifyAll()
```
and the loop in `put()` will suddenly by infinite when the first thread is resumed. In PY2.7 (due to our dummy `_qsize()` hardcoded to return 1) this was not the case. Thus setting `q.maxsize` will not have the desired effect of an unlimited queue size at first.

In the stacktrace, this happens in `_produce`, i.e. `FirstPipelineThread`, but the same problem should occur with `MiddlePipelineThread`. `MiddlePipelineThread` and `LastPipelineThread` are probably prone to the same in `in_queue.get()`. Did not have a look at that.

Unfortunately, the simple safeguard employed in our queue invalidation (`q.mutex.acquire`) does not prevent this as the `threading.Condition`s `not_empty` and `not_full` release it when waited upon. I'm not sure whether replacing `q.maxsize` on a queue that is currently in use is considered a supported thing by python, and this in turn a python bug. One solution from our side could be to do
```python
        q.maxsize = 2
        q._qsize = _qsize  # always returns 1
```
which due to replacing `q._put` and `q._get` with our dummies would result in a queue that is never full and never empty just the same.

NOTE: Be careful with debug prints and file writes, they can affect timing sufficiently to let the test pass :confounded:

**Comment by sampsyo** [comment] 2016-06-28 18:36
***Whoa*** -- that's some impressive detective work, @wordofglass! I'm impressed, and I'm also impressed at how miserable the problem is. In retrospect, the pipeline invalidation thing was definitely a hack -- we need a way to empty out a queue and instruct threads to shut down, but surely we can find a less invasive way to accomplish that. I'll add this to my to-do list.

**Comment by sampsyo** [comment] 2016-06-28 18:38
On reading again, @wordofglass, your proposed solution (maxsize = 2) looks like it would work. It's still a hack, I suppose, but it seems to me that it will solve this particular problem.

And it can't be over-emphasized: nice work tracking this down.

**Comment by jrobeson** [comment] 2016-06-28 21:10
yeah, good work figuring this one out @wordofglass  .  I think you should submit a PR since you discovered it :)

**Comment by wordofglass** [comment] 2016-06-28 23:29
Thanks :blush:

Btw, the change in Python was in [#10110](http://bugs.python.org/issue10110):
> There were no guarantees about the behavior when maxsize is changed, nor should we make such guarantees.

@sampsyo: So should this go in right now? Or leave it be for the time being since PY3 support is not there yet and you might come with a different, less-hacky solution before this gets relevant?

**Comment by sampsyo** [comment] 2016-06-29 01:35
Tellingly:

> The change from == to <= is innocuous.

In any case, let's put this workaround in now. I'll continue to look for a better solution, but a duct-tape solution will be nice to have in the mean time.

**Closed** 2018-11-18 00:00 UTC
Labels: python 3
